=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/dtd/language.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by aa (aa) -->
<!--DTD generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->

<!-- Root elements -->

<!ELEMENT root ((defaultLanguage),(languageSet+))>

<!ELEMENT defaultLanguage EMPTY>
<!ATTLIST defaultLanguage
	language CDATA #REQUIRED
	country CDATA #IMPLIED
>

<!ELEMENT languageSet (definition*,copyDefFrom*) >
<!ATTLIST languageSet
	language CDATA #REQUIRED
	country CDATA #IMPLIED
>

<!ELEMENT definition EMPTY>
<!ATTLIST definition
	encoding CDATA #REQUIRED
	charset CDATA #REQUIRED
	direction CDATA #REQUIRED
	imagesDirectoryName CDATA #IMPLIED
	flagImage CDATA #IMPLIED
>

<!ELEMENT copyDefFrom EMPTY>
<!ATTLIST copyDefFrom
	fromLanguage CDATA #REQUIRED
	fromCountry CDATA #REQUIRED
>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/languages/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "language.dtd">
<root>

	<defaultLanguage language="he" country="IL"/>	

	<languageSet language="he" country="IL" >
		<definition charset="UTF-8"  encoding="UTF-8" direction="rtl" flagImage="israel.gif" imagesDirectoryName="heb"/>
	</languageSet>
	
	<languageSet language="en" country="US" >
		<definition charset="UTF-8"  encoding="UTF-8" direction="ltr" flagImage="use.gif" imagesDirectoryName="eng"/>
	</languageSet> 

	<languageSet language="iw" country="IL">
		<copyDefFrom fromLanguage="he" fromCountry="IL" />
	</languageSet>
	
	<languageSet language="iw">
		<copyDefFrom fromLanguage="he" fromCountry="IL" />
	</languageSet> 

</root>
