=== odedns/oldsrc/src/WorkSrc/igsi/mataf/MatafServer/Web Content/dse/desktop/desktop.dtd
<?xml version="1.0" encoding = "ISO-8859-1" ?>
<!ELEMENT Desktop (BookmarkArea?,CustomizableArea*,ScenarioArea?,CustomizableArea*,(WorkingArea|TaskArea|SplitArea|CustomizableArea|TaskInfo)*)>
<!ATTLIST Desktop
	title CDATA "desktop_title"
	width CDATA  "800" 
	height CDATA "600"
	lookAndFeel CDATA #IMPLIED
	finalizerClass CDATA #IMPLIED
	finalizerMethod CDATA #IMPLIED
	helpFileURL CDATA #IMPLIED
	initializerClass CDATA #IMPLIED
	initializerMethod CDATA #IMPLIED
	rebuilderClass CDATA #IMPLIED
	rebuilderMethod CDATA #IMPLIED
	multiTasking (true|false) "false"
	onInitialize CDATA #IMPLIED
	orientation CDATA "LEFT_TO_RIGHT"
	packages CDATA #IMPLIED>

<!ELEMENT LanguageBox EMPTY>
<!ATTLIST LanguageBox
	width CDATA "94"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	name CDATA #IMPLIED
	languages CDATA #REQUIRED>


<!ELEMENT TaskInfo EMPTY>
<!ATTLIST TaskInfo
	taskName CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	shortDescription CDATA #REQUIRED
	longDescription CDATA #REQUIRED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	code CDATA #REQUIRED
	executeOperation (true|false) "false">

<!-- TaskInfos are the place to save short and log descriptions -->
<!-- Parameters are like this par1,par2,par3 They are in operation constructors -->

<!-- ScenarioArea -->

<!ELEMENT ScenarioArea (Scenario)+>
<!ATTLIST ScenarioArea
	width CDATA "600"
	name CDATA #IMPLIED
	height CDATA "82">

<!ELEMENT SplitArea (ScenarioArea|TaskArea|WorkingArea|CustomizableArea)+>
<!ATTLIST SplitArea
	width CDATA "977"
	height CDATA "457"
	orientation (HORIZONTAL|VERTICAL) "HORIZONTAL">

<!ELEMENT Scenario (ButtonRow|MenuButtonRow)+>
<!ATTLIST Scenario
	label CDATA #REQUIRED
	name CDATA #IMPLIED
	hotKey CDATA #IMPLIED>

<!ELEMENT ButtonRow (TaskLauncherButton)+>
<!ATTLIST ButtonRow
	width CDATA "372"
	height CDATA "25"
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	name CDATA #IMPLIED
	hSpace CDATA "2"
	vSpace CDATA "2">
<!ELEMENT TaskLauncherButton EMPTY>
<!ATTLIST TaskLauncherButton
	name CDATA #IMPLIED
	label CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "90"
	height CDATA "22"
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	taskName CDATA #REQUIRED 
	enabled (true|false) #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	hotKey CDATA #IMPLIED
	mnemonic CDATA #IMPLIED
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT MenuButtonRow (MenuButton+)>
<!ATTLIST MenuButtonRow
	width CDATA "140"
	height CDATA "25"
	hSpace CDATA "2"
	vSpace CDATA "2">

<!ELEMENT MenuButton (MenuItem+,Separator*)+>
<!ATTLIST MenuButton
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	circularNavigation (true|false) "true"
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT Separator EMPTY>

<!ELEMENT MenuItem EMPTY>
<!ATTLIST MenuItem
	label CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	name CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	mnemonic CDATA #IMPLIED
	taskName CDATA #REQUIRED
	toolTipText CDATA #IMPLIED>

<!ELEMENT Tree (TreeNode+)>
<!ATTLIST Tree
	name CDATA "Tree"
	width CDATA "307"
	height CDATA "457"
	backgroundNonSelectionColor CDATA #IMPLIED
	backgroundSelectionColor CDATA #IMPLIED
	foregroundNonSelectionColor CDATA #IMPLIED
	foregroundSelectionColor CDATA #IMPLIED
	iconName CDATA #IMPLIED
	hotKey CDATA #IMPLIED
	label CDATA #IMPLIED>

<!ELEMENT TreeNode (TreeNode|LeafTreeNode)+>
<!ATTLIST TreeNode
	backgroundNonSelectionColor CDATA #IMPLIED
	backgroundSelectionColor CDATA #IMPLIED
	foregroundNonSelectionColor CDATA #IMPLIED
	foregroundSelectionColor CDATA #IMPLIED
	iconName CDATA #IMPLIED
	name CDATA #IMPLIED
	label CDATA #IMPLIED
	toolTipText CDATA #IMPLIED>

<!ELEMENT LeafTreeNode EMPTY>
<!ATTLIST LeafTreeNode
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	taskName CDATA #REQUIRED 
	backgroundNonSelectionColor CDATA #IMPLIED
	backgroundSelectionColor CDATA #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	foregroundNonSelectionColor CDATA #IMPLIED
	foregroundSelectionColor CDATA #IMPLIED
	iconName CDATA #IMPLIED
	label CDATA #IMPLIED
	toolTipText CDATA #IMPLIED>

<!-- CustomizableArea -->

<!ELEMENT CustomizableArea (LanguageBox|DateField|Timer|ExitButton|IconButton|TextField|IconLabel|Label|MultipleStateIconLabel|MenuButton|Tree|TaskLauncherTextField|ExternalApplicationButton|MessageArea|TaskLauncherButton|BookmarkArea)+>
<!ATTLIST CustomizableArea
	name CDATA #REQUIRED
	name CDATA #IMPLIED
	width CDATA "237"
	height CDATA "82">

<!ELEMENT IconButton EMPTY>
<!ATTLIST IconButton
	name CDATA #IMPLIED
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	aplication CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	taskName CDATA #REQUIRED
	enabled (true|false) #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>


<!ELEMENT ExternalApplicationButton EMPTY>
<!ATTLIST ExternalApplicationButton 
	name CDATA #IMPLIED
	command CDATA #REQUIRED
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	enabled (true|false) #IMPLIED
	hotKey CDATA #IMPLIED
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>


<!ELEMENT TextField EMPTY>
<!ATTLIST TextField
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	horizontalAlignment CDATA "0"
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED
	text CDATA #IMPLIED>

<!ELEMENT MessageArea EMPTY>
<!ATTLIST MessageArea
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED
	text CDATA #IMPLIED
	intNumberOfTasks CDATA #IMPLIED
	showMessageArea (true|false) #IMPLIED
	informationLevel CDATA #IMPLIED>
	
<!ELEMENT TaskLauncherTextField EMPTY>
<!ATTLIST TaskLauncherTextField
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	delimChar CDATA #IMPLIED
	horizontalAlignment CDATA "0"
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED	
	prefix CDATA #IMPLIED
	suffix CDATA #IMPLIED
	text CDATA #IMPLIED>

<!ELEMENT Timer EMPTY>
<!ATTLIST Timer
	name CDATA  #FIXED "Timer" 
	width CDATA "40"
	height CDATA "20"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	horizontalAlignment CDATA "0"
	onInitialize CDATA #IMPLIED
	pattern CDATA "HH:mm">

<!ELEMENT DateField EMPTY>
<!ATTLIST DateField
	name CDATA  #FIXED "DateField" 
	width CDATA "75"
	height CDATA "20"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	horizontalAlignment CDATA "0"
	onInitialize CDATA #IMPLIED
	pattern CDATA "dd/MM/yy">

<!ELEMENT IconLabel EMPTY>
<!ATTLIST IconLabel
	iconName CDATA #REQUIRED
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT MultipleStateIconLabel (IconState+)>
<!ATTLIST MultipleStateIconLabel
	name CDATA #REQUIRED
	width CDATA "11"
	height CDATA "20"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	onInitialize CDATA #IMPLIED>

<!ELEMENT IconState EMPTY>
<!ATTLIST IconState
	name CDATA #REQUIRED
	icon CDATA #REQUIRED>

<!ELEMENT Label EMPTY>
<!ATTLIST Label
	label CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	name CDATA #IMPLIED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT ExitButton EMPTY>
<!ATTLIST ExitButton
	name CDATA #FIXED "ExitButton" 
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	confirmationWindowTitle CDATA "Confirmation"
	confirmationWindowMessage CDATA "confirmationWindowMessage" 
	confirmationWindowYesTitle CDATA "confirmationWindowYesTitle"
	confirmationWindowNoTitle CDATA "confirmationWindowNoTitle"
	onInitialize CDATA #IMPLIED>
	
<!-- There must be one and only one ExitButton in the Desktop -->

<!-- WorkingArea -->

<!ELEMENT WorkingArea EMPTY>
<!ATTLIST WorkingArea
   	name CDATA #FIXED "WorkingArea"
	iconName CDATA #REQUIRED
	defaultIcon CDATA #REQUIRED
	width CDATA "730"
	warningMessageWhenAViewCanNotBeClosed CDATA "ViewErrormessage"
	showPopup (true|false) "true"
	height CDATA "457"
	xCascade CDATA "22"
	color  CDATA #IMPLIED
	redGreenBlue CDATA #IMPLIED 
	yCascade CDATA "22">

<!-- TaskArea -->

<!ELEMENT BookmarkArea (Bookmark*)>
<!ATTLIST BookmarkArea
	name CDATA #REQUIRED
	width CDATA "95"
	height CDATA "457"
	hSpace CDATA "4"
	vSpace CDATA "4"
	bookmarkWidth CDATA "70"
	bookmarkHeight CDATA "22"
	iconName CDATA "/images/ExButt32.gif"	
	alignment CDATA #REQUIRED>

<!ELEMENT Bookmark EMPTY>
<!ATTLIST Bookmark
	label CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	taskName CDATA #REQUIRED 
	executeOperation (true|false) "false"
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED>

<!ELEMENT TaskArea EMPTY>
<!ATTLIST TaskArea
    name CDATA #FIXED "TaskArea"
	width CDATA "489"
	height CDATA "30"
	hSpace CDATA "2"
	vSpace CDATA "2"
	taskWidth CDATA "80"
	taskHeight CDATA "25"
	baseHotKey CDATA "ALT"
	substituteHotKey CDATA "SHIFT"
	maxNumberOfTasks CDATA "5"
	errorMessageWhenClassNotExist CDATA "ClassErrorMessage"
	warningMessageWhenMaxNumberOfTasksReached CDATA "WarningMaxTasks">

=== odedns/oldsrc/src/WorkSrc/igsi/mataf/MatafServer/Web Content/dse_bt/desktop/desktop.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Desktop SYSTEM "desktop.dtd" >
<Desktop finalizerClass="com.ibm.dse.samples.aa.desktop.OpenTellerDesktop" finalizerMethod="exit" helpFileURL="http://localhost:9080/DSE_TellerSampleApplicationWeb/dse/onlineinfo/onlinehelp.hs" width="977" height="630">
  <ScenarioArea>
    <Scenario label="Sessions" hotKey="CTRL+1">
      <ButtonRow>
        <TaskLauncherButton label="Change_password"     	toolTipText="Teller_change_password"   	mnemonic="P" taskName="CHGPW"/>
        <TaskLauncherButton label="Start_customer_session" 	toolTipText="Start_customer_session" 	mnemonic="S" taskName="SCUST"/>
        <TaskLauncherButton label="User_Profiles" 		toolTipText="Teller_user_profile"  	mnemonic="U" taskName="USRP"/>
        <TaskLauncherButton label="User_Roles"        		toolTipText="Teller_roles"      	mnemonic="R" taskName="ROLES"/>
      </ButtonRow>
      <ButtonRow>
	<TaskLauncherButton label="End_Of_Day"        	toolTipText="End_Of_Day"          	mnemonic="A" taskName="EODO"/>
        <TaskLauncherButton label="Logon"         	toolTipText="Teller_logon"           	mnemonic="O" taskName="LGON"/>
        <TaskLauncherButton label="Logoff"        	toolTipText="Teller_logoff"          	mnemonic="F" taskName="LGOFF"/>  
        <TaskLauncherButton label="ForcedLogon"      	toolTipText="Teller_forced_logon"      	mnemonic="G" taskName="FLGON"/>
      </ButtonRow>
      <MenuButtonRow>
        <MenuButton hotKey="CTRL+T" toolTipText="Teller_session" iconName="/images/969.gif">
          <MenuItem label="Teller_user_profile" mnemonic="U" taskName="USRP"/>
          <Separator/>
          <MenuItem label="Teller_roles" mnemonic="R" taskName="ROLES"/>
          <Separator/>
          <MenuItem label="Teller_change_password" mnemonic="P" taskName="CHGPW"/>
          <Separator/>
          <MenuItem label="Teller_logon" mnemonic="O" taskName="LGON"/>
          <Separator/>
          <MenuItem label="Teller_forced_logon" mnemonic="G" taskName="FLGON"/>
          <Separator/>
          <MenuItem label="Teller_logoff" mnemonic="F" taskName="LGOFF"/>
          <Separator/>
          <MenuItem label="End_Of_Day" mnemonic="A" taskName="EODO"/>
        </MenuButton>
        <MenuButton hotKey="CTRL+C" toolTipText="Customer_session" iconName="/images/055.gif">
           <MenuItem label="Start_customer_session" mnemonic="S" taskName="SCUST"/>
        </MenuButton>
      </MenuButtonRow>
    </Scenario>
    <Scenario label="TellerOperations" hotKey="CTRL+2">
      <ButtonRow>
        <TaskLauncherButton label="Deposit"      toolTipText="Deposit"      mnemonic="D" taskName="DEPO"/>
        <TaskLauncherButton label="Withdrawal"   toolTipText="Withdrawal"   mnemonic="W" taskName="WITH"/>
        <TaskLauncherButton label="Bill_payment" toolTipText="Bill_payment" mnemonic="B" taskName="BILL"/>
      </ButtonRow>
      <ButtonRow>
        <TaskLauncherButton label="Accounts_List"    toolTipText="Accounts_List"    mnemonic="L" taskName="ACLS"/>
        <TaskLauncherButton label="Accounts_History" toolTipText="Accounts_History" mnemonic="H" taskName="ACHS"/>
	    <TaskLauncherButton label="Teller_Reconcile_Query" toolTipText="Teller_Reconcile_Query" mnemonic="R" taskName="TRQO"/>	
      </ButtonRow>
      <MenuButtonRow>
        <MenuButton hotKey="CTRL+F" toolTipText="Financial_operations" iconName="/images/963.gif">
          <MenuItem label="Accounts_List"    mnemonic="L" taskName="ACLS"/>
          <MenuItem label="Accounts_History" mnemonic="H" taskName="ACHS"/>
	    
        </MenuButton>
        <MenuButton hotKey="CTRL+Q" toolTipText="Account_Queries" iconName="/images/1300.gif">
          <MenuItem label="Withdrawal" 		mnemonic="W" taskName="WITH"/>
          <MenuItem label="Deposit"    		mnemonic="D" taskName="DEPO"/>
          <MenuItem label="Bill_payment"        mnemonic="B" taskName="BILL"/>
        </MenuButton>
      </MenuButtonRow>
    </Scenario>
    <Scenario label="Teller" hotKey="CTRL+3">
      <ButtonRow>
        <TaskLauncherButton label="Electronic_journal"    toolTipText="Electronic_journal" mnemonic="J" taskName="EJRN"/>
        <TaskLauncherButton label="Teller_Exchange_Query" toolTipText="Teller_Exchange_Query" mnemonic="T" taskName="EXCH"/>
      </ButtonRow>
      <ButtonRow>
        <TaskLauncherButton label="Branch_Totals"       toolTipText="Branch_Totals"     mnemonic="L" taskName="TOTS"/>
        <TaskLauncherButton label="Branch_settle" 	toolTipText="Branch_settle"   	mnemonic="B" taskName="BSTL"/>
	<TaskLauncherButton label="CashSettleQuery" 	toolTipText="Cash_Settlement_Query"   	mnemonic="C" taskName="CSTL"/>
      </ButtonRow>
      <MenuButtonRow width="180">
        <MenuButton toolTipText="Electronic_journal" iconName="/images/075.gif">
          <MenuItem label="Electronic_journal" mnemonic="J" taskName="EJRN"/>
        </MenuButton>
        <MenuButton toolTipText="Exchanges" iconName="/images/906.gif">
          <MenuItem label="Teller_exchange" mnemonic="X" taskName="EXCH"/>
        </MenuButton>
        <MenuButton toolTipText="Administration" iconName="/images/355.gif">
          <MenuItem label="Branch_Totals"   mnemonic="T" taskName="TOTS"/>
          <MenuItem label="Branch_settle"   mnemonic="B" taskName="BSTL"/>
          <Separator/>
          <MenuItem label="Cash_Settlement_Query" mnemonic="C" taskName="CSTL"/>
        </MenuButton>
      </MenuButtonRow>
    </Scenario>
    <Scenario label="Cash_drawers" hotKey="CTRL+4">
      <ButtonRow width="462">
	    <TaskLauncherButton label="CD_Management"  toolTipText="CD_Management"    mnemonic="M" taskName="CDMGT"/>
      </ButtonRow>
      <ButtonRow width="462">
        <TaskLauncherButton label="Bins/Batches" toolTipText="Bins/Batches" mnemonic="B" taskName="BBADM"/>
	    <TaskLauncherButton label="CD_Totals"    toolTipText="CD_Totals"          mnemonic="T" taskName="CDTOT"/>
      </ButtonRow>
      <MenuButtonRow width="70">
        <MenuButton width="32" toolTipText="Cash_drawers" iconName="/images/036.gif">
          <MenuItem label="CD_Management" mnemonic="M" taskName="CDMGT"/>
          <Separator/>
          <MenuItem label="Bins/Batches"  mnemonic="B" taskName="BBADM"/>
          <MenuItem label="CD_Totals"	  mnemonic="T" taskName="CDTOT"/>
        </MenuButton>
      </MenuButtonRow>
    </Scenario>
  </ScenarioArea>
  <CustomizableArea width="297" height="82" name="CA1">
    <Label width="100" height="20" label="Client_Name" y="0" x="15"/>
    <TextField width="100" height="20" text="IBM" focusTraversable="false" name="CLIENT_NAME" y="17" x="15"/>
    <Label width="100" height="20" label="Client_ID" y="35" x="15"/>
    <TextField width="100" height="20" text="13234" focusTraversable="false" name="CLIENT_ID" y="53" x="15"/>
    <IconLabel width="112" height="20" y="35" x="150" iconName="/images/452.gif"/>
    <IconLabel height="32" onClick="reBuild()" y="2" x="260" iconName="/images/rebuild.gif"/>
  </CustomizableArea>
  <CustomizableArea width="80" height="82" name="CA2">
    <IconLabel height="27" y="2" x="24" iconName="/images/logo.gif"/>
    <MenuButton y="32" x="24" toolTipText="Operations" iconName="/images/954.gif">
      <MenuItem label="Teller_user_profile" mnemonic="U" taskName="USRP"/>
      <Separator/>
      <MenuItem label="Teller_roles" mnemonic="R" taskName="ROLES"/>
      <Separator/>
      <MenuItem label="Teller_change_password" mnemonic="P" taskName="CHGPW"/>
      <Separator/>
      <MenuItem label="Teller_logon" mnemonic="O" taskName="LGON"/>
      <Separator/>
      <MenuItem label="Teller_forced_logon" mnemonic="G" taskName="FLGON"/>
      <Separator/>
      <MenuItem label="Teller_logoff" mnemonic="F" taskName="LGOFF"/>
      <Separator/>
      <MenuItem label="End_Of_Day" mnemonic="A" taskName="EODO"/>
      <Separator/>
      <MenuItem label="Start_customer_session" mnemonic="S" taskName="SCUST"/>
    </MenuButton>
  </CustomizableArea>
  <SplitArea orientation="HORIZONTAL" width="977" height="457">
  <CustomizableArea width="247" height="457" name="TreeArea">
    <Tree label="TellerOperations" hotKey="CTRL+H" backgroundSelectionColor="white" iconName="/images/336.gif">
      <TreeNode label="Sessions" backgroundSelectionColor="yellow" toolTipText="Teller/Customer_sessions" iconName="/images/355.gif">
        <LeafTreeNode label="User_Profiles"	toolTipText="Teller_user_profile"	iconName="/images/051.gif" taskName="USRP"/>
        <LeafTreeNode label="User_Roles"	toolTipText="Teller_roles"		iconName="/images/051.gif" taskName="ROLES"/>
        <LeafTreeNode label="Change_password"	toolTipText="Teller_change_password"	iconName="/images/051.gif" taskName="CHGPW"/>
        <LeafTreeNode label="Logon"         	toolTipText="Teller_logon"           	iconName="/images/051.gif" taskName="LGON"/>
        <LeafTreeNode label="ForcedLogon"      	toolTipText="Teller_forced_logon"      	iconName="/images/051.gif" taskName="FLGON"/>
        <LeafTreeNode label="Logoff"        	toolTipText="Teller_logoff"          	iconName="/images/051.gif" taskName="LGOFF"/>
        <LeafTreeNode label="End_Of_Day"        	toolTipText="End_Of_Day"          	iconName="/images/051.gif" taskName="EODO"/>
        <LeafTreeNode label="Start_customer_session" 	toolTipText="Start_customer_session" 	iconName="/images/051.gif" taskName="SCUST"/>
      </TreeNode>
      <TreeNode label="Operations" backgroundSelectionColor="yellow" toolTipText="Financial/Query_operations" iconName="/images/355.gif">
        <LeafTreeNode label="Deposit"          toolTipText="Deposit"      iconName="/images/051.gif" taskName="DEPO"/>
        <LeafTreeNode label="Withdrawal"       toolTipText="Withdrawal"   iconName="/images/051.gif" taskName="WITH"/>
