=== odedns/oldsrc/src/WorkSrc/igsi/mataf/MatafServer/Web Content/dse/desktop/matafdesktop.dtd
<?xml version="1.0" encoding = "ISO-8859-1" ?>
<!ELEMENT Desktop (BookmarkArea?,MatafCustomizableArea*,ScenarioArea?,MatafCustomizableArea*,(MatafWorkingArea|TaskArea|SplitArea|MatafCustomizableArea|TaskInfo|MatafTaskInfo)*)>
<!ATTLIST Desktop
	title CDATA "desktop_title"
	width CDATA  "1020" 
	height CDATA "743"
	lookAndFeel CDATA #IMPLIED
	finalizerClass CDATA #IMPLIED
	finalizerMethod CDATA #IMPLIED
	helpFileURL CDATA #IMPLIED
	initializerClass CDATA #IMPLIED
	initializerMethod CDATA #IMPLIED
	rebuilderClass CDATA #IMPLIED
	rebuilderMethod CDATA #IMPLIED
	multiTasking (true|false) "false"
	onInitialize CDATA #IMPLIED
	orientation CDATA "RIGHT_TO_LEFT"
	packages CDATA #IMPLIED>

<!ELEMENT LanguageBox EMPTY>
<!ATTLIST LanguageBox
	width CDATA "94"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	name CDATA #IMPLIED
	languages CDATA #REQUIRED>


<!ELEMENT TaskInfo EMPTY>
<!ATTLIST TaskInfo
	taskName CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	shortDescription CDATA #REQUIRED
	longDescription CDATA #REQUIRED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	code CDATA #REQUIRED
	executeOperation (true|false) "true">

<!-- TaskInfos are the place to save short and log descriptions -->
<!-- Parameters are like this par1,par2,par3 They are in operation constructors -->

<!-- ScenarioArea -->

<!ELEMENT ScenarioArea (Scenario)+>
<!ATTLIST ScenarioArea
	width CDATA "1020"
	name CDATA #IMPLIED
	height CDATA "82">

<!ELEMENT SplitArea (ScenarioArea|TaskArea|MatafWorkingArea|MatafCustomizableArea)+>
<!ATTLIST SplitArea
	width CDATA "977"
	height CDATA "457"
	orientation (HORIZONTAL|VERTICAL) "HORIZONTAL">

<!ELEMENT Scenario (ButtonRow|MenuButtonRow)+>
<!ATTLIST Scenario
	label CDATA #REQUIRED
	name CDATA #IMPLIED
	hotKey CDATA #IMPLIED>

<!ELEMENT ButtonRow (TaskLauncherButton)+>
<!ATTLIST ButtonRow
	width CDATA "372"
	height CDATA "25"
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	name CDATA #IMPLIED
	hSpace CDATA "2"
	vSpace CDATA "2">
<!ELEMENT TaskLauncherButton EMPTY>
<!ATTLIST TaskLauncherButton
	name CDATA #IMPLIED
	label CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "90"
	height CDATA "22"
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	taskName CDATA #REQUIRED 
	enabled (true|false) #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	hotKey CDATA #IMPLIED
	mnemonic CDATA #IMPLIED
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT MenuButtonRow (MenuButton+)>
<!ATTLIST MenuButtonRow
	width CDATA "140"
	height CDATA "25"
	hSpace CDATA "2"
	vSpace CDATA "2">

<!ELEMENT MenuButton (MenuItem+,Separator*)+>
<!ATTLIST MenuButton
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	circularNavigation (true|false) "true"
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT Separator EMPTY>

<!ELEMENT MenuItem EMPTY>
<!ATTLIST MenuItem
	label CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	name CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	mnemonic CDATA #IMPLIED
	taskName CDATA #REQUIRED
	toolTipText CDATA #IMPLIED>

<!ELEMENT Tree (TreeNode+)>
<!ATTLIST Tree
	name CDATA "Tree"
	width CDATA "307"
	height CDATA "457"
	backgroundNonSelectionColor CDATA #IMPLIED
	backgroundSelectionColor CDATA #IMPLIED
	foregroundNonSelectionColor CDATA #IMPLIED
	foregroundSelectionColor CDATA #IMPLIED
	iconName CDATA #IMPLIED
	hotKey CDATA #IMPLIED
	label CDATA #IMPLIED>

<!ELEMENT TreeNode (TreeNode|LeafTreeNode)+>
<!ATTLIST TreeNode
	backgroundNonSelectionColor CDATA #IMPLIED
	backgroundSelectionColor CDATA #IMPLIED
	foregroundNonSelectionColor CDATA #IMPLIED
	foregroundSelectionColor CDATA #IMPLIED
	iconName CDATA #IMPLIED
	name CDATA #IMPLIED
	label CDATA #IMPLIED
	toolTipText CDATA #IMPLIED>

<!ELEMENT LeafTreeNode EMPTY>
<!ATTLIST LeafTreeNode
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	taskName CDATA #REQUIRED 
	backgroundNonSelectionColor CDATA #IMPLIED
	backgroundSelectionColor CDATA #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	foregroundNonSelectionColor CDATA #IMPLIED
	foregroundSelectionColor CDATA #IMPLIED
	iconName CDATA #IMPLIED
	label CDATA #IMPLIED
	toolTipText CDATA #IMPLIED>
	
<!ELEMENT IconButton EMPTY>
<!ATTLIST IconButton
	name CDATA #IMPLIED
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	aplication CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	taskName CDATA #REQUIRED
	enabled (true|false) #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>


<!ELEMENT ExternalApplicationButton EMPTY>
<!ATTLIST ExternalApplicationButton 
	name CDATA #IMPLIED
	command CDATA #REQUIRED
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	enabled (true|false) #IMPLIED
	hotKey CDATA #IMPLIED
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>


<!ELEMENT TextField EMPTY>
<!ATTLIST TextField
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	horizontalAlignment CDATA "0"
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED
	text CDATA #IMPLIED>

<!ELEMENT MessageArea EMPTY>
<!ATTLIST MessageArea
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED
	text CDATA #IMPLIED
	intNumberOfTasks CDATA #IMPLIED
	showMessageArea (true|false) #IMPLIED
	informationLevel CDATA #IMPLIED>
	
<!ELEMENT TaskLauncherTextField EMPTY>
<!ATTLIST TaskLauncherTextField
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	delimChar CDATA #IMPLIED
	horizontalAlignment CDATA "0"
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED	
	prefix CDATA #IMPLIED
	suffix CDATA #IMPLIED
	text CDATA #IMPLIED>

<!ELEMENT Timer EMPTY>
<!ATTLIST Timer
	name CDATA  #FIXED "Timer" 
	width CDATA "40"
	height CDATA "20"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	horizontalAlignment CDATA "0"
	onInitialize CDATA #IMPLIED
	pattern CDATA "HH:mm">

<!ELEMENT DateField EMPTY>
<!ATTLIST DateField
	name CDATA  #FIXED "DateField" 
	width CDATA "70"
	height CDATA "20"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	horizontalAlignment CDATA "0"
	onInitialize CDATA #IMPLIED
	pattern CDATA "dd/MM/yy">

<!ELEMENT IconLabel EMPTY>
<!ATTLIST IconLabel
	iconName CDATA #REQUIRED
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT MultipleStateIconLabel (IconState+)>
<!ATTLIST MultipleStateIconLabel
	name CDATA #REQUIRED
	width CDATA "11"
	height CDATA "20"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	onInitialize CDATA #IMPLIED>

<!ELEMENT IconState EMPTY>
<!ATTLIST IconState
	name CDATA #REQUIRED
	icon CDATA #REQUIRED>

<!ELEMENT Label EMPTY>
<!ATTLIST Label
	label CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	name CDATA #IMPLIED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT ExitButton EMPTY>
<!ATTLIST ExitButton
	name CDATA #FIXED "ExitButton" 
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	confirmationWindowTitle CDATA "Confirmation"
	confirmationWindowMessage CDATA "confirmationWindowMessage" 
	confirmationWindowYesTitle CDATA "confirmationWindowYesTitle"
	confirmationWindowNoTitle CDATA "confirmationWindowNoTitle"
	onInitialize CDATA #IMPLIED>
	
<!-- There must be one and only one ExitButton in the Desktop -->
<!-- TaskArea -->

<!ELEMENT BookmarkArea (Bookmark*)>
<!ATTLIST BookmarkArea
	name CDATA #REQUIRED
	width CDATA "95"
	height CDATA "457"
	hSpace CDATA "4"
	vSpace CDATA "4"
	bookmarkWidth CDATA "70"
	bookmarkHeight CDATA "22"
	iconName CDATA "/images/ExButt32.gif"	
	alignment CDATA #REQUIRED>

<!ELEMENT Bookmark EMPTY>
<!ATTLIST Bookmark
	label CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	taskName CDATA #REQUIRED 
	executeOperation (true|false) "false"
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED>

<!ELEMENT TaskArea EMPTY>
<!ATTLIST TaskArea
    name CDATA #FIXED "TaskArea"
	width CDATA "1020"
	height CDATA "0"
	hSpace CDATA "2"
	vSpace CDATA "2"
	taskWidth CDATA "80"
	taskHeight CDATA "25"
	baseHotKey CDATA "ALT"
	substituteHotKey CDATA "SHIFT"
	maxNumberOfTasks CDATA "5"
	errorMessageWhenClassNotExist CDATA "ClassErrorMessage"
	warningMessageWhenMaxNumberOfTasksReached CDATA "WarningMaxTasks">
	
	
<!-- Definitions for Mataf Desktop Beans - will replace all above defines...-->

<!-- MatafCustomizableArea -->
<!ELEMENT MatafCustomizableArea (LanguageBox|DateField|Timer|ExitButton|IconButton|TextField|IconLabel|Label|Tree|TaskLauncherTextField|ExternalApplicationButton|MessageArea|TaskLauncherButton|BookmarkArea|MatafMultipleStateIconLabel|MatafMenuBar|MatafMenuButton|MenuButtonRow|MatafMessageArea|MatafIconButton)+>
<!ATTLIST MatafCustomizableArea
	name CDATA #REQUIRED
	name CDATA #IMPLIED
	width CDATA "237"
	height CDATA "82"
	backgroundColor CDATA "186,194,222">

<!-- MatafWorkingArea -->
<!ELEMENT MatafWorkingArea EMPTY >
<!ATTLIST MatafWorkingArea
   	name CDATA #FIXED "MatafWorkingArea"
	iconName CDATA #IMPLIED
	defaultIcon CDATA #IMPLIED
	width CDATA "1020"
	warningMessageWhenAViewCanNotBeClosed CDATA "ViewErrormessage"
	showPopup (true|false) "true"
	height CDATA "665"
	xCascade CDATA "22"
	color  CDATA #IMPLIED
	redGreenBlue CDATA #IMPLIED 
	yCascade CDATA "22">
	
<!ELEMENT MatafMenuBar (MatafMenu|MenuButton)*>
<!ATTLIST MatafMenuBar
	name CDATA #REQUIRED
	foregroundColor CDATA "255,255,255"
	backgroundColor CDATA "125,140,150" 
	orientation CDATA "RIGHT_TO_LEFT"
	font CDATA "Tahoma,bold,11"
	menuSize CDATA #IMPLIED
>

<!ELEMENT MatafMenu (MatafMenuItem|Separator|MatafMenu)*>
<!ATTLIST MatafMenu
	label CDATA #REQUIRED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	parameters CDATA #IMPLIED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	mnemonic CDATA #IMPLIED
	toolTipText CDATA #IMPLIED
	orientation CDATA "RIGHT_TO_LEFT"
	foregroundColor CDATA "255,255,255"	
	backgroundColor CDATA "125,140,150" 
	font CDATA "Arial,plain,12"
	taskName CDATA "Non-Specified"
>

<!ELEMENT MatafMenuItem EMPTY>	
<!ATTLIST MatafMenuItem
	label CDATA #REQUIRED
	iconName CDATA #IMPLIED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA "true"	
	mnemonic CDATA #IMPLIED	
	toolTipText CDATA #IMPLIED
	orientation CDATA "RIGHT_TO_LEFT"
	foregroundColor CDATA "255,255,255"
	backgroundColor CDATA "125,140,150" 
	font CDATA "Arial,plain,12"
	taskName CDATA #IMPLIED
	visualAction (true|false) "false"
	remoteTransaction (true|false) "true"
	newAction (yes|no) "no"
>

<!ELEMENT MatafMenuButton (MatafMenuItem+,Separator*)+>
<!ATTLIST MatafMenuButton
	name CDATA #REQUIRED
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	circularNavigation (true|false) "true"
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED>

<!ELEMENT MatafMessageArea EMPTY>
<!ATTLIST MatafMessageArea
	name CDATA #IMPLIED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	focusTraversable (true|false) #IMPLIED
	hotKey CDATA #IMPLIED
	onInitialize CDATA #IMPLIED
	text CDATA #IMPLIED
	intNumberOfTasks CDATA #IMPLIED
	showMessageArea (true|false) #IMPLIED
	informationLevel CDATA #IMPLIED>
	
<!ELEMENT MatafIconButton EMPTY>
<!ATTLIST MatafIconButton
	name CDATA #IMPLIED
	iconName CDATA #REQUIRED
	toolTipText CDATA #REQUIRED
	width CDATA "32"
	height CDATA "22"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	aplication CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	code CDATA #IMPLIED
	parameters CDATA #IMPLIED
	shortDescription CDATA #IMPLIED
	longDescription CDATA #IMPLIED
	executeOperation CDATA #IMPLIED
	taskName CDATA #REQUIRED
	enabled (true|false) #IMPLIED
	errorMessageOnInstantiateOperation CDATA "OperationerrorMessage"
	onClick CDATA #IMPLIED
	onMouseEntered CDATA #IMPLIED
	onMouseExited CDATA #IMPLIED
	onInitialize CDATA #IMPLIED
	visualAction CDATA #IMPLIED>
	
<!ELEMENT MatafTaskInfo EMPTY>
<!ATTLIST MatafTaskInfo
	taskName CDATA #REQUIRED
	operation CDATA #IMPLIED
	process CDATA #IMPLIED
	application CDATA #IMPLIED
	operationPanel CDATA #IMPLIED
	shortDescription CDATA #REQUIRED
	longDescription CDATA #REQUIRED
	yNavigationArea CDATA #IMPLIED
	xNavigationArea CDATA #IMPLIED
	widthNavigationArea CDATA #IMPLIED
	heightNavigationArea CDATA #IMPLIED
	code CDATA #REQUIRED
	connectionToHost  (dontCare|true|false) #REQUIRED
	branchStatus  (dontCare|open|closed) #REQUIRED
	workstationStatus  (dontCare|open|closed) #REQUIRED
	cashRegisterStatus  (dontCare|open|closed) #REQUIRED
	cashRegisterType  (dontCare|teller|foreignCurrency) #REQUIRED
	connectionToPrinter  (dontCare|true|false) #REQUIRED
	transactionType  (dontCare|credit|debit) #REQUIRED
	operationType (transaction|query) #REQUIRED
	executeOperation (true|false) "true">
	
<!ELEMENT MatafMultipleStateIconLabel (MatafIconState+)>
<!ATTLIST MatafMultipleStateIconLabel
	name CDATA #REQUIRED
	width CDATA "11"
	height CDATA "20"
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	onInitialize CDATA #IMPLIED>

<!ELEMENT MatafIconState EMPTY>
<!ATTLIST MatafIconState
	name CDATA #REQUIRED
	icon CDATA #REQUIRED
	toolTipText CDATA #IMPLIED>

=== odedns/oldsrc/src/WorkSrc/igsi/mataf/MatafServer/Web Content/dse/desktop/matafdesktop.xml
<?xml version="1.0" encoding="ISO-8859-8"?>
<!DOCTYPE Desktop SYSTEM "matafdesktop.dtd">
<Desktop rebuilderClass="mataf.dse.appl.OpenDesktop" rebuilderMethod="rebuild" finalizerClass="mataf.dse.appl.OpenDesktop" finalizerMethod="exit" height="743" width="1024" packages="mataf.desktop.beans." lookAndFeel="javax.swing.plaf.ocean.OceanLookAndFeel">


	<!--==============================MENU=============================-->
	
	<MatafCustomizableArea height="21" name="area1" width="1020">
		<MatafMenuBar name="mainMenu" menuSize="1019,20">

<MatafMenu taskName="1000" label="שאילתות" mnemonic="ש" font="Arial,BOLD,12">
	 <MatafMenu taskName="1100" label="מטבע ישראלי" mnemonic="י">
		 <MatafMenuItem label="101 ברור יתרה" operation="activateRTTransactionOp" taskName="1101" />
		 <MatafMenuItem label="103 40 תנועות אחרונות" operation="activateRTTransactionOp" taskName="1103" />
		 <MatafMenuItem label="104 שיקים שהופקדו בחשבון" operation="activateRTTransactionOp" taskName="1104" />
		 <MatafMenuItem label="105 שיקים מבוטלים" operation="activateRTTransactionOp" taskName="1105" />
		 <MatafMenuItem label="107 שיקים לפי פרטי ח-ן נמשך" operation="activateRTTransactionOp" taskName="1107" />
		 <MatafMenuItem label="108 ניכיון שיקים" operation="activateRTTransactionOp" taskName="1108" />
		 <MatafMenuItem label="110 זיהוי טלפוני" operation="activateRTTransactionOp" taskName="1110" />
		 <MatafMenuItem label="113 תנועות אחרונות" operation="activateRTTransactionOp" taskName="1113" />
		 <MatafMenuItem label="114 תנועות ידניות בח-ן960/961" operation="activateRTTransactionOp" taskName="1114" />
		 <MatafMenuItem label="119 חשבונות מעבר וחריגים" operation="activateRTTransactionOp" taskName="1119" />
		 <MatafMenuItem label="120 תנועות מהיום" operation="activateRTTransactionOp" taskName="1120" />
		 <MatafMenuItem label="121 ברור משכורות לחשבון" operation="activateRTTransactionOp" taskName="1121" />
		 <MatafMenuItem label="122 פירוט תדפיסים/פקסים" operation="activateRTTransactionOp" taskName="1122" />
		 <MatafMenuItem label="130 ברור מספר מסלקה" operation="activateRTTransactionOp" taskName="1130" />
		 <MatafMenuItem label="131 קוד קבלת/מסירת מידע" operation="activateRTTransactionOp" taskName="1131" />
		 <MatafMenuItem label="134 העברות מט''י הסטוריות" operation="activateRTTransactionOp" taskName="1134" />
		 <MatafMenuItem label="135 ברור חשבונות מוטבים" operation="activateRTTransactionOp" taskName="1135" />
		 <MatafMenuItem label="153 מעקב פעולות בהוראות קבע" operation="activateRTTransactionOp" taskName="1153" />
		 <MatafMenuItem label="154 מעקב פע.חיובים ע''פ הרשאה" operation="activateRTTransactionOp" taskName="1154" />
		 <MatafMenuItem label="155 פירוט הרשאות לחשבון" operation="activateRTTransactionOp" taskName="1155" />
		 <MatafMenu taskName="1150" label="המחאות מעותדות" >
			 <MatafMenuItem label="140 המחאות לפי לקוח" operation="activateRTTransactionOp" taskName="1140" />
			 <MatafMenuItem label="141 המחאות לפי חותם" operation="activateRTTransactionOp" taskName="1141" />
			 <MatafMenuItem label="142 המחאות לפי תאריך" operation="activateRTTransactionOp" taskName="1142" />
			 <MatafMenuItem label="143 הסטוריה להמחאה" operation="activateRTTransactionOp" taskName="1143" />
			 <MatafMenuItem label="144 המחאות שנפרעו ללקוח" operation="activateRTTransactionOp" taskName="1144" />
			 <MatafMenuItem label="145 המחאות-ברור מונים" operation="activateRTTransactionOp" taskName="1145" />
			 <MatafMenuItem label="146 המחאות סיכום" operation="activateRTTransactionOp" taskName="1146" />
		 </MatafMenu>
		 <MatafMenuItem label="199 שאילתה כללית" operation="activateRTTransactionOp" taskName="1199" />
	 </MatafMenu>
	 <MatafMenu taskName="1200" label="ני''ע כללי" mnemonic="נ">
		 <MatafMenuItem label="201 שערי ני''ע" operation="activateRTTransactionOp" taskName="1201" />
		 <MatafMenuItem label="203 יתרות לנייר" operation="activateRTTransactionOp" taskName="1203" />
		 <MatafMenuItem label="204 ברור לקבוצה" operation="activateRTTransactionOp" taskName="1204" />
		 <MatafMenuItem label="205 הודעות ני''ע" operation="activateRTTransactionOp" taskName="1205" />
		 <MatafMenuItem label="206 גילוי נאות" operation="activateRTTransactionOp" taskName="1206" />
		 <MatafMenuItem label="209 מדדי מעו''ף" operation="activateRTTransactionOp" taskName="1209" />
		 <MatafMenuItem label="210 פרטי נייר רצף/מעו''ף" operation="activateRTTransactionOp" taskName="1210" />
		 <MatafMenuItem label="220 טיקר" operation="activateRTTransactionOp" taskName="1220" />
		 <MatafMenuItem label="222 טיקר - חו''ל" operation="activateRTTransactionOp" taskName="1222" />
		 <MatafMenuItem label="223 גרפיט" operation="activateRTTransactionOp" taskName="1223" />
		 <MatafMenuItem label="224 מחץ לחלונות" operation="activateRTTransactionOp" taskName="1224" />
		 <MatafMenuItem label="225 מגמה 2000" operation="activateRTTransactionOp" taskName="1225" />
		 <MatafMenuItem label="226 מנתא" operation="activateRTTransactionOp" taskName="1226" />
	 </MatafMenu>
	 <MatafMenu taskName="1300" label="מטבע חוץ" mnemonic="מ">
		 <MatafMenuItem label="301 תיק מט''ח ללקוח" operation="activateRTTransactionOp" taskName="1301" />
		 <MatafMenuItem label="302 תיק מט''ח לחשבון" operation="activateRTTransactionOp" taskName="1302" />
		 <MatafMenuItem label="303 תיק מט''ח לפי מטבע" operation="activateRTTransactionOp" taskName="1303" />
		 <MatafMenuItem label="304 תיק מט''ח לפי סוג ח-ן" operation="activateRTTransactionOp" taskName="1304" />
		 <MatafMenuItem label="305 הודעות מח''ץ" operation="activateRTTransactionOp" taskName="1305" />
		 <MatafMenuItem label="306 שערי מטבע ל-'יום קודם'" operation="activateRTTransactionOp" taskName="1306" />
		 <MatafMenuItem label="307 תנועות מט''ח ללקוח" operation="activateRTTransactionOp" taskName="1307" />
		 <MatafMenuItem label="308 תיק מט''ח" operation="activateRTTransactionOp" taskName="1308" />
		 <MatafMenuItem label="309 בירור החזרי מס למט''ח" operation="activateRTTransactionOp" taskName="1309" />
		 <MatafMenuItem label="310 שערים למסחר בשער מוסכם" operation="activateRTTransactionOp" taskName="1310" />
		 <MatafMenuItem label="311 בירור חדר עיסקאות" operation="activateRTTransactionOp" taskName="1311" />
		 <MatafMenuItem label="312 המרה ממטבע למטבע" operation="activateRTTransactionOp" taskName="1312" />
		 <MatafMenuItem label="313 העברות מט''ח יוצאות" operation="activateRTTransactionOp" taskName="1313" />
		 <MatafMenuItem label="314 מנויים לפקס בתקבולי מט''ח" operation="activateRTTransactionOp" taskName="1314" />
		 <MatafMenuItem label="315 פעולות חדר עסקאות" operation="activateRTTransactionOp" taskName="1315" />
		 <MatafMenuItem label="316 שערי מטבע היסטוריים" operation="activateRTTransactionOp" taskName="1316" />
		 <MatafMenuItem label="317 תנועות מט''ח היסטוריות" operation="activateRTTransactionOp" taskName="1317" />
		 <MatafMenuItem label="325 נתוני חשבון פקדוני" operation="activateRTTransactionOp" taskName="1325" />
		 <MatafMenuItem label="326 פירוט מוצרים מובנים" operation="activateRTTransactionOp" taskName="1326" />
		 <MatafMenuItem label="328 עסקות סחר חוץ" operation="activateRTTransactionOp" taskName="1328" />
		 <MatafMenuItem label="335 נתוני הלוואה" operation="activateRTTransactionOp" taskName="1335" />
	 </MatafMenu>
	 <MatafMenu taskName="1400" label="אשראי והלוואות" mnemonic="ר">
		 <MatafMenuItem label="401 תיק הלוואות לחשבון" operation="activateRTTransactionOp" taskName="1401" />
		 <MatafMenuItem label="402 תיק הלוואות לעמית" operation="activateRTTransactionOp" taskName="1402" />
		 <MatafMenuItem label="404 טבלת סוגי הלוואות" operation="activateRTTransactionOp" taskName="1404" />
		 <MatafMenuItem label="405 עלות אפקטיבית" operation="activateRTTransactionOp" taskName="1405" />
		 <MatafMenuItem label="406 בדיקת קיום שיעבוד" operation="activateRTTransactionOp" taskName="1406" />
		 <MatafMenuItem label="409 שאילתת משכנתאות" operation="activateRTTransactionOp" taskName="1409" />
		 <MatafMenuItem label="410 משכנתאות לפי זהות" operation="activateRTTransactionOp" taskName="1410" />
		 <MatafMenuItem label="415 ריביות למשכנתאות" operation="activateRTTransactionOp" taskName="1415" />
		 <MatafMenuItem label="421 פרטי אובליגנט" operation="activateRTTransactionOp" taskName="1421" />
		 <MatafMenuItem label="422 אובליגו חריגים בסניף" operation="activateRTTransactionOp" taskName="1422" />
		 <MatafMenuItem label="423 אובליגו דו''ח 1" operation="activateRTTransactionOp" taskName="1423" />
		 <MatafMenuItem label="424 אובליגו דו''ח 4" operation="activateRTTransactionOp" taskName="1424" />
		 <MatafMenuItem label="425 דו''ח פעילות לקוח" operation="activateRTTransactionOp" taskName="1425" />
		 <MatafMenuItem label="426 דו''ח אובליגו" operation="activateRTTransactionOp" taskName="1426" />
		 <MatafMenuItem label="427 דוח חריגים לאובליגו" operation="activateRTTransactionOp" taskName="1427" />
		 <MatafMenuItem label="430 פרוט שעבוד לחשבון" operation="activateRTTransactionOp" taskName="1430" />
		 <MatafMenuItem label="440 פרוט נתוני חברה" operation="activateRTTransactionOp" taskName="1440" />
		 <MatafMenuItem label="450 פרטי בטחון" operation="activateRTTransactionOp" taskName="1450" />
		 <MatafMenuItem label="460 אישורי חיובים למסב" operation="activateRTTransactionOp" taskName="1460" />
		 <MatafMenuItem label="470 ערבויות" operation="activateRTTransactionOp" taskName="1470" />
	 </MatafMenu>
	 <MatafMenu taskName="1500" label="השקעות" mnemonic="ה">
		 <MatafMenuItem label="501 פקדונות ללקוח" operation="activateRTTransactionOp" taskName="1501" />
		 <MatafMenuItem label="502 תיק פקדונות לחשבון" operation="activateRTTransactionOp" taskName="1502" />
		 <MatafMenuItem label="503 פקדון לפי מספר" operation="activateRTTransactionOp" taskName="1503" />
		 <MatafMenuItem label="510 נתוני קרנות למורים" operation="activateRTTransactionOp" taskName="1510" />
