=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWEJB/ejbModule/ejbResources/config/legacy/legacy.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root elements -->

<!ELEMENT root (LegacyCommand | Record | Structure)*>

<!ELEMENT LegacyCommand (CallArgument*,LegacyObjectGraph)>
<!ATTLIST LegacyCommand
	commandName CDATA #REQUIRED
	commandType (SP | OS400) #REQUIRED
	sqlStatement CDATA #IMPLIED
	connectionManagerName CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
	libraryName CDATA #IMPLIED
	programName CDATA #IMPLIED
>

<!ELEMENT CallArgument EMPTY>
<!ATTLIST CallArgument
	name CDATA #REQUIRED
	type  (integer | long | double | decimal | float | string | date | timestamp | time) #REQUIRED
	inputType (in | out | inout) #REQUIRED
	inputContainerGetter CDATA #IMPLIED
	resultAs (simple | structure) #IMPLIED
	simpleResultSetter CDATA #IMPLIED
>

<!ELEMENT LegacyObjectGraph (NodeRecord*, ArgumentStructureDefinition*)>
<!ATTLIST LegacyObjectGraph
	className CDATA #REQUIRED
>

<!ELEMENT NodeRecord (NodeRecord*)>
<!ATTLIST NodeRecord
	id CDATA #REQUIRED
	resultSetNumber CDATA #REQUIRED
	adder CDATA #IMPLIED
	parentIdAttribute CDATA #IMPLIED
>

<!ELEMENT ArgumentStructureDefinition (NodeStructure+)>
<!ATTLIST ArgumentStructureDefinition
	name CDATA #REQUIRED
	structureIdLength CDATA #REQUIRED
>

<!ELEMENT NodeStructure (NodeStructure*)>
<!ATTLIST NodeStructure
	id CDATA #REQUIRED
	adder CDATA #IMPLIED
>

<!ELEMENT Record (RecordField+)>
<!ATTLIST Record
	id CDATA #REQUIRED
	className CDATA #REQUIRED
>

<!ELEMENT RecordField EMPTY>
<!ATTLIST RecordField
	columnId CDATA #REQUIRED
	columnType (integer | long | double | decimal | float | string | date | timestamp | time) #IMPLIED
	attributeId CDATA #REQUIRED
	attributeType (integer | long | double | decimal | float | string | date | timestamp | time) #IMPLIED
	fromMask CDATA #IMPLIED
	uniqueId (true | false) #IMPLIED
	setter CDATA #IMPLIED
>

<!ELEMENT Structure (StructureField+)>
<!ATTLIST Structure
	id CDATA #REQUIRED
	className CDATA #REQUIRED
	length CDATA #REQUIRED
>

<!ELEMENT StructureField EMPTY>
<!ATTLIST StructureField
	startPosition CDATA #REQUIRED
	length CDATA #REQUIRED
	fromMask CDATA #IMPLIED
	attributeId CDATA #REQUIRED
	attributeType (integer | long | double | decimal | float | string | date | timestamp | time) #REQUIRED
	setter CDATA #IMPLIED
>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/legacy/test1.xml
<?xml version="1.0" encoding="utf-8" ?> 
<!DOCTYPE root SYSTEM "legacy.dtd">

<root>


	<Structure id="envST" className="com.ness.test.legacy2.Env2" length="14">
		<StructureField startPosition="0"  length="3" attributeId="id" attributeType="integer"/>
	    <StructureField startPosition="3" length="5" attributeId="desc" attributeType="string" />
		<StructureField startPosition="8"  length="3" attributeId="x1" attributeType="integer"/> 
	    <StructureField startPosition="11" length="1" attributeId="x2" attributeType="integer" /> 
		<StructureField startPosition="12"  length="2" attributeId="x3" attributeType="integer"/>
	</Structure>      

	
	<Structure id="cstST" className="com.ness.test.legacy2.Customer2" length="46">
	        <StructureField startPosition="0"  length="3" attributeId="id" attributeType="integer"/>
	        <StructureField startPosition="3" length="5" attributeId="firstName" attributeType="string" />
	        <StructureField startPosition="8" length="10" attributeId="lastName" attributeType="string" />
	        <StructureField startPosition="18" length="10" attributeId="telephone" attributeType="integer" setter="setHomeTelephone"/>
	        <StructureField startPosition="28" length="8"  attributeId="birthDate" attributeType="date" fromMask="ddMMyyyy" />
	        <StructureField startPosition="36" length="10"  attributeId="exception" attributeType="string"/>
	</Structure>      

	<Structure id="Profession" className="com.ness.test.legacy2.CustomerProfession2" length="6">
	        <StructureField startPosition="0"  length="3" attributeType="integer" attributeId="customerId"/>
	        <StructureField startPosition="3"  length="3" attributeType="integer" attributeId="professionId"/>
	</Structure>      

	<Structure id="AddressSTR" className="com.ness.test.legacy2.CustomerAddress2" length="24">
	        <StructureField startPosition="0"  length="3" attributeType="integer" attributeId="id"/>
	        <StructureField startPosition="3"  length="5" attributeType="string" attributeId="city"/>
	        <StructureField startPosition="8"  length="10" attributeType="string" attributeId="street"/>
	        <StructureField startPosition="18"  length="1" attributeType="integer" attributeId="main"/>
	</Structure>      

	<Structure id="TelephoneS" className="com.ness.test.legacy2.Telephone2" length="21">
	        <StructureField startPosition="0"  length="3" attributeType="integer" attributeId="customerId"/>
	        <StructureField startPosition="3"  length="9" attributeType="string" attributeId="telephone"/>
	        <StructureField startPosition="12"  length="9" attributeType="integer" attributeId="fax"/>
	</Structure>      

	<Structure id="ExceptionS" className="com.ness.test.legacy2.Telephone2" length="21">
	        <StructureField startPosition="0"  length="3" attributeType="integer" attributeId="customerId"/>
	        <StructureField startPosition="3"  length="9" attributeType="string" attributeId="telephone"/>
	        <StructureField startPosition="12"  length="9" attributeType="integer" attributeId="fax"/>
	</Structure>      


	<LegacyCommand commandName="testCMD4" commandType="SP" sqlStatement="call SP_LEGACY_TST1(?,?,?,?,?,?)" >	
	        <CallArgument name="VAR01" type="integer" inputType="in" inputContainerGetter="getArg1Value"/>
	        <CallArgument name="VAR02" type="integer" inputType="in" />
	        <CallArgument name="VAR03" type="integer" inputType="in" />	        
	        <CallArgument name="VAR04" type="integer" inputType="out" resultAs="simple" simpleResultSetter="setOutArg1"/>	        
	        <CallArgument name="VAR05" type="string" inputType="out" resultAs="structure"/>	
	        <CallArgument name="VAR06" type="string" inputType="out" resultAs="structure"/>

	        <LegacyObjectGraph className="com.ness.test.legacy2.LegacyObjectGraph2">

				<ArgumentStructureDefinition name="VAR05" structureIdLength="5">
					<NodeStructure id="cstST" adder="addCustomer" >
						<NodeStructure id="Profession" adder="addProfession"/>
						<NodeStructure id="AddressSTR" adder="addAddress">
							<NodeStructure id="TelephoneS" adder="addTelephone"/>
						</NodeStructure> 						
					</NodeStructure>
				</ArgumentStructureDefinition>	
				
				<ArgumentStructureDefinition name="VAR06" structureIdLength="5">
					<NodeStructure id="envST" adder="addEnv"></NodeStructure>
				</ArgumentStructureDefinition>
				
	         </LegacyObjectGraph>
	         
	</LegacyCommand>

</root>
