=== odedns/oldsrc/src/WorkSrc/igsi/mataf/MatafServer/Web Content/dtd/dsectxt.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT dsectxt.xml (context+)>

<!ELEMENT context ((refService)*,(refKColl | refType)?)*>
<!ATTLIST context 
    implClass CDATA #IMPLIED
    parent CDATA #IMPLIED
    type CDATA #REQUIRED
    id ID #REQUIRED
>

<!ELEMENT refKColl (iniValue)*>
<!ATTLIST refKColl 
    refId CDATA #REQUIRED
>

<!ELEMENT refType EMPTY>
<!ATTLIST refType
	refId IDREF #REQUIRED
>

<!ELEMENT refService EMPTY>
<!ATTLIST refService
	refId CDATA #REQUIRED
	alias CDATA #REQUIRED
	type CDATA #REQUIRED
>

<!ELEMENT iniValue EMPTY>
<!ATTLIST iniValue
	value CDATA #REQUIRED
	name IDREF #REQUIRED
>

=== odedns/oldsrc/src/WorkSrc/igsi/mataf/MatafServer/Web Content/dse/server/dsectxt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dsectxt.xml SYSTEM "../../dtd/dsectxt.dtd">
<dsectxt.xml>
	<!--DWGroupDef:Server.Contexts-->
	<!-- SERVER CONTEXT DEFs.=================================================== -->
	<!--=========================================================================-->
	<!-- Branch Context                                                          -->
	<!--=========================================================================-->
	<context id="branchServer" parent="nil" type="branch">
		<refKColl refId="branchData" />
		<refService refId="JDBCServicesConnMgr" alias="connectionManager" type="cs" />
		<refService alias="CSServer" refId="realCSServer" type="cs" />
		<refService refId="communicationsPool" alias="pool" type="pool"/>
		<refService refId="cicsService" alias="testCICSService" type="cs" />
		<refService refId="refTables" alias="refTablesService" type="cs" />
		<refService refId="msgsHandler" alias="msgsHandlerService" type="cs" />
		<refService refId="noDataAccount" alias="noDataAccount" type="cs" />
		<refService refId="snifin" alias="snifin" type="cs" />
		<refService refId="realJournal" alias="testJournal" type="journal"/>
		<!--refService refId="journalService" alias="journalService" type="journal"/-->
		<refService refId="HAST_CH_LO_MEDUVACH" alias="HAST_CH_LO_MEDUVACH" type="cs"/>
		<refService refId="HAST_TAVLAT_HACHLATA" alias="HAST_TAVLAT_HACHLATA" type="cs"/>
		<refService refId="HAST_SUG_PEULA" alias="HAST_SUG_PEULA" type="cs"/>
		<refService refId="PERSONAL_MENU" alias="PERSONAL_MENU" type="cs"/>
	</context>
	<!--=========================================================================-->
	<!-- Java Channel Context                                                    -->
	<!--=========================================================================-->
	<context id="javaChannelCtx" parent="branchServer" type="op">
		<refKColl refId="javaChannelData" />
	</context>

	<!--=========================================================================-->
	<!-- Java Session Context                                                    -->
	<!--=========================================================================-->
	<context id="javaSessionCtx" type="op">
		<refKColl refId="javaSessionData" />
	</context>


	<!--=========================================================================-->
	<!-- Startup Operation Context                                               -->
	<!--=========================================================================-->
	<context id="startupServerCtx" parent="branchServer" type="op">
		<refKColl refId="startupServerData" />
	</context>
	<!--=========================================================================-->
	<!-- End session Operation Context                                           -->
	<!--=========================================================================-->
	<context id="endSessionServerCtx" type="op">
		<refKColl refId="endSessionServerData" />
	</context>

	<!--=========================================================================-->
	<!-- Test Transaction Context                                       -->
	<!--=========================================================================-->
	<context id="testTrxCtx" type="op">
		<refKColl refId="testTrxData" />
	</context>

	<!-- for ref tables  -->
	<context id="refTablesCtx" type="op">
		<refKColl refId="refTablesData" />
		<refService refId="refTables" alias="refTablesService" type="cs" />
	</context>
	<!-- context for generic CS mechanism -->
	<context id="genOpCtx" type="op">
		<refKColl refId="genOpData" />
	</context>
	
	<!--=========================================================================-->
	<!-- CICS Test Operation Context                                       -->
	<!--=========================================================================-->
	<context id="cicsTestServerCtx" parent="branchServer" type="op">
		<refKColl refId="emptyData" />
	</context>
	
	<!--=========================================================================-->
	<!-- Empty Context 						                                     -->
	<!--=========================================================================-->
	<context id="emptyCtx" type="op">
		<refKColl refId="emptyData" />
	</context>
	
	
	<!--========================================================================-->
	<!-- Sample JDBC Table Opeartion Context									-->
	<!--========================================================================-->
	<context id="JDBCCtx" parent="branchServer" type="op">
		<refKColl refId="JDBCTableData" />
	</context>
	
	<!--========================================================================-->
	<!-- Electronic Journal Sample operation Context							-->
	<!--========================================================================-->
	<context id="journalOpCtx" parent="branchServer" type="op">
		<refKColl refId="toJournalData" />
	</context>
	
	<!-- ================================================================== -->
	<!-- 				Electronic Journal				      -->
	<!-- ================================================================== -->
	<!--context id="retrieveSchemaInfoServerCtx" type="op">
		<refKColl refId="retrieveSchemaInfoServerData" />
	</context-->
	<!-- Context definition for the Electronic Jouranl Query operation-->
	<!--context id="ejServerCtx" type="op">
		<refKColl refId="ejServerData" />
	</context-->
	
	<!-- override context -->
	<context id="overrideCtx" type="op">
		<refKColl refId="overrideData" />
		<refService refId="matafOverrideTable" alias="overrideTable" type="cs" />
	</context>	
	
	<context id="matafOverrideTableCtx" type="op">
          <refKColl refId="matafOverrideTableData" />
          <refService alias="connectionManager" refId="JDBCServicesConnMgr" type="cs" />
     </context>

	<context id="journalWrapCtx" type="op">
		<refKColl refId="journalWrapData" />
     </context>	
	<!--/DWGroupDef-->
	
	<!--=========================================================================-->
	<!-- T410 (סליקה) Context                             				         -->
	<!--=========================================================================-->
	<context id="slikaCtx" parent="branchServer" type="op">
		<refKColl refId="slikaData" />
		<refService refId="journalSlikaService" alias="journalService" type="journal"/>
		<refService refId="GLST_IFYUN" alias="GLST_IFYUN" type="cs"/>
		<refService refId="GLST_IFYUN_2" alias="GLST_IFYUN_2" type="cs"/>
		<refService refId="TLST_HIYUV_AM_SCHUM" alias="TLST_HIYUV_AM_SCHUM" type="cs"/>
		<!--refService refId="journalT410ChotemService" alias="journalT410ChotemService" type="journal"/>
		<refService refId="journalT410MutavService" alias="journalT410MutavService" type="journal"/-->
	</context>
	
	<!--=========================================================================-->
	<!-- K86P (הלבנת הון) Context                          				         -->
	<!--=========================================================================-->
	<context id="halbanathonCtx" parent="branchServer" type="op">
		<refKColl refId="halbanathonData" />
	</context>
	
	<!--========================================================================-->
	<!-- Srika (T491) Opeartion Context											-->
	<!--========================================================================-->
	<context id="scanJournalCtx" parent="branchServer" type="op">
		<refService refId="realJournal" alias="journalService" type="journal"/>
		<refKColl refId="srikaData" />
	</context>
	
	<context id="srikaRestoreCtx" type="op">
		<refKColl refId="srikaRestoreData" />
		<refService refId="journalSlikaService" alias="journalService" type="journal"/>
	</context>
	<!--========================================================================-->
	<!-- Transaction Validations Opeartion Context											-->
	<!--========================================================================-->
	<context id="validatorCtx" parent="branchServer" type="op">
		<refKColl refId="validatorData" />
	</context>
	<!--========================================================================-->
	<!-- Empty context chained to branch context 								-->
	<!--========================================================================-->
	<context id="emptyCtxChainedToBranchCtx" parent="branchServer" type="op">
		<refKColl refId="emptyData" />
	</context>
	
</dsectxt.xml>
