=== odedns/oldsrc/src/WorkSrc/igsi/mataf/MatafServer/Web Content/dse_bt/branch/branchSpecifications.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="branchSpecifications">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="branchOperationMode"/>
				<xs:element ref="branchWeeklyOpenTimeLimits"/>
				<xs:element ref="branchHolidays"/>
				<xs:element ref="branchScheduledEvents"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="branchOperationMode">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:maxExclusive value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="branchWeeklyOpenTimeLimits">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="branchOpenTimeLimit" maxOccurs="8"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="branchOpenTimeLimit">
		<xs:complexType>
			<xs:attribute name="dayOfWeek">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:maxExclusive value="8"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="timeOfDay" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="branchHolidays">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="weekdayHolidays"/>
				<xs:element ref="allMonthsHolidays"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="weekdayHolidays">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dayOfWeek" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dayOfWeek">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:maxExclusive value="8"/>
				<xs:minExclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="allMonthsHolidays">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="monthlyHolidays" maxOccurs="unbounded"/>
				<xs:element ref="endMonthlyHolidays"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="monthlyHolidays">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="daysOfMonth" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="monthlyDaysOfWeek"/>
			</xs:sequence>
			<xs:attribute name="monthValue" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="daysOfMonth">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dayOfMonth" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dayOfMonth">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minExclusive value="0"/>
				<xs:maxExclusive value="32"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="monthlyDaysOfWeek">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="monthlyDayOfWeek" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="monthlyDayOfWeek">
		<xs:complexType>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:maxExclusive value="8"/>
						<xs:minExclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="order" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="endMonthlyHolidays"/>
	<xs:element name="branchScheduledEvents">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="scheduledEvent" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scheduledEvent">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="dayOfWeek" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:maxExclusive value="8"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="timeOfDay" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== odedns/oldsrc/src/WorkSrc/igsi/mataf/MatafServer/Web Content/dse_bt/branch/branchSpecifications.xml
<?xml version="1.0" encoding="UTF-8"?>
<branchSpecifications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="branchSpecifications.xsd">
	<!-- branchOperationMode is the mode in which a branch operates -->
	<!-- branchOperationMode is an integer where 0 stands for no am/pm and 1 stands for am/pm mode -->
	<branchOperationMode>0</branchOperationMode>
	
	<!-- branchWeeklyOpenTimeLimits is a list of the daily time limits before which a branch cannot open -->
	<branchWeeklyOpenTimeLimits>
		<!-- branchOpenTimeLimit has two attributes. -->
		<!-- dayOfWeek which is an integer, where 1 is Sunday, 2 is Monday and so on -->
		<!-- if dayOfWeek is set to 0, it means the time applies for any day of the week -->
		<!-- timeOfDay which is a string in the form of 14:30, where 14:30 corresponds to 2:30 pm -->
		<branchOpenTimeLimit dayOfWeek = "2" timeOfDay = "7:30"/>
		<branchOpenTimeLimit dayOfWeek = "3" timeOfDay = "7:30"/>
		<branchOpenTimeLimit dayOfWeek = "4" timeOfDay = "7:30"/>
		<branchOpenTimeLimit dayOfWeek = "5" timeOfDay = "7:30"/>
		<branchOpenTimeLimit dayOfWeek = "6" timeOfDay = "7:30"/>
		<branchOpenTimeLimit dayOfWeek = "7" timeOfDay = "9:30"/>
	</branchWeeklyOpenTimeLimits>
	<!-- branchHolidays are the days of the year that a branch would not treat as business days -->
	<branchHolidays>
		<!-- weekdayHolidays is a weekly list containing the repeating days of the week -->
		<!-- in the year that will be treated as non business days -->
		<weekdayHolidays>
			<!-- dayOfWeek is an integer where 1 corresponds to Sunday and so on -->
			<dayOfWeek>7</dayOfWeek>
			<dayOfWeek>1</dayOfWeek>
		</weekdayHolidays>
		<!-- allMonthsHolidays is a monthly list containing the days of -->
		<!-- the year that will be treated as non business days -->
		<allMonthsHolidays>
			<!-- monthlyHolidays contains the days of a specific month -->
			<!-- in the year that will be treated as non business days -->
			<!-- monthValue is an integer where 1 corresponds to January  and so on -->
			<monthlyHolidays monthValue="1">
				<!-- daysOfMonth is list of the days of a month that are non business days -->
				<daysOfMonth>
					<!-- dayOfMonth is an integer between 1 and 31 -->
					<dayOfMonth>1</dayOfMonth>
				</daysOfMonth>
				<!-- monthlyDayOfWeek is an integer where value=2 corresponds to Monday and so on -->
				<!-- The order=1 corresponds to the first Monday of the specified month -->
				<monthlyDaysOfWeek>
					<monthlyDayOfWeek value="2" order="1"/>
				</monthlyDaysOfWeek>
			</monthlyHolidays>
			<monthlyHolidays monthValue="12">
				<daysOfMonth>
					<dayOfMonth>25</dayOfMonth>
					<dayOfMonth>26</dayOfMonth>
				</daysOfMonth>
				<monthlyDaysOfWeek>
					<monthlyDayOfWeek value="6" order="2"/>
				</monthlyDaysOfWeek>
			</monthlyHolidays>
			<monthlyHolidays monthValue="6">
				<monthlyDaysOfWeek>
					<monthlyDayOfWeek value="2" order="1"/>
					<monthlyDayOfWeek value="3" order="1"/>
				</monthlyDaysOfWeek>
			</monthlyHolidays>
			<!-- endMonthlyHolidays a required tag to help with the parsing -->
			<endMonthlyHolidays/>
		</allMonthsHolidays>
	</branchHolidays>

	<!-- branchScheduledEvents identifies times and dates for each event to be executed -->
	<branchScheduledEvents>
		<!-- scheduledEvent has three attributes. -->
		<!-- name which is a unique string identifying the event -->
		<!-- dayOfWeek which is an integer, where 1 is Sunday, 2 is Monday and so on -->
		<!-- If dayOfWeek was set to "0", it means that it applies for any day of the week -->
		<!-- timeOfDay which is a string in the form of 14:30, where 14:30 corresponds to 2:30 pm -->

		<!-- pmSwitchTime is the time when a branch switches business day -->
		<scheduledEvent name = "pmSwitchTime" dayOfWeek = "2" timeOfDay = "14:30"/>
		<scheduledEvent name = "pmSwitchTime" dayOfWeek = "3" timeOfDay = "14:30"/>
		<scheduledEvent name = "pmSwitchTime" dayOfWeek = "4" timeOfDay = "14:30"/>
		<scheduledEvent name = "pmSwitchTime" dayOfWeek = "5" timeOfDay = "14:30"/>
		<scheduledEvent name = "pmSwitchTime" dayOfWeek = "6" timeOfDay = "14:30"/>
		<scheduledEvent name = "pmSwitchTime" dayOfWeek = "7" timeOfDay = "12:30"/>
		
		<!-- pmForceSwitchTime is the time during which any teller logging on -->
		<!-- will be forced to be logged on for the next business day -->
		<scheduledEvent name = "pmForceSwitchTime" dayOfWeek = "0" timeOfDay = "14:30"/>

		<!-- pmSwitchOptionTime could be used as the time before switch time during which -->
		<!-- a teller has the option to log on the current business day or the next -->
		<scheduledEvent name = "pmSwitchOptionTime" dayOfWeek = "0" timeOfDay = "2:30"/>

		<!-- pmSwitchWarningTime is the time period before switch time during which -->
		<!-- the teller gets a message that the switch time is approaching -->
		<scheduledEvent name = "pmSwitchWarningTime" dayOfWeek = "0" timeOfDay = "2:00"/>
	</branchScheduledEvents>
</branchSpecifications>
