=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/dtd/flower.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by aa (aa) -->
<!--DTD generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->

<!-- Root elements -->

<!ELEMENT root (validationCheckDefinition | validationCheck | validationCheckSet | buttonSet | flowImplementations | validator | guardDefinition | structureDefinition | typeDefinition | context | contextElementSetDefinition | operationDefinition | serviceDefinition | activityDefinition | flow | formatterDefinition)*>

<!-- Generic elements -->

<!ELEMENT param EMPTY>
<!ATTLIST param
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!ELEMENT implementation EMPTY>
<!ATTLIST implementation
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>


<!-- Flow definitions -->

<!ELEMENT flowImplementations (implementation*)>

<!ELEMENT flow (tabSystemData?, actionList*, state+)>
<!ATTLIST flow
	name CDATA #REQUIRED
	context CDATA #IMPLIED
	independent (true | false) #IMPLIED
	menu CDATA #IMPLIED
	defaultInternalTransitions (true | false) #IMPLIED
	validator CDATA #IMPLIED
	type (tabSystem | generic) #IMPLIED
	implementation CDATA  #IMPLIED
	authId CDATA #IMPLIED
>

<!ELEMENT tabSystemData EMPTY>
<!ATTLIST tabSystemData
	page CDATA #REQUIRED
>


<!-- Action definitions -->

<!ELEMENT action (param*)>
<!ATTLIST action
	type (operation | actionList | service) #REQUIRED
	refName CDATA #REQUIRED
	methodName CDATA #IMPLIED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
>

<!ELEMENT actionList (action*)>
<!ATTLIST actionList
	name CDATA #REQUIRED
>

<!-- Type Definition definitions -->

<!ELEMENT builderTypeDefinition (param*)>
<!ATTLIST builderTypeDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!ELEMENT builder EMPTY>
<!ATTLIST builder
	fromType CDATA #IMPLIED
	builderTypeName CDATA #IMPLIED
	method CDATA #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT printer EMPTY>
<!ATTLIST printer
	builderTypeName CDATA #IMPLIED
	method CDATA #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT builders (builder+)>

<!ELEMENT type (builders?, printer?)>
<!ATTLIST type
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	xiType (true | false) #IMPLIED
	basicXIType CDATA #IMPLIED
>

<!ELEMENT typeDefinition (type | builderTypeDefinition)*>

<!-- Structure definitions -->

<!ELEMENT structureField EMPTY>
<!ATTLIST structureField
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	defaultValue CDATA #IMPLIED
>

<!ELEMENT structureDefinition (structureField*)>
<!ATTLIST structureDefinition
	name CDATA #REQUIRED
>


<!-- Context definitions -->

<!ELEMENT context (service | field | contextElementSet)*>
<!ATTLIST context
	name CDATA #REQUIRED
	type (dynamic | static) #IMPLIED
	parent CDATA #IMPLIED
	addOnDemand (true | false) #IMPLIED
>

<!ELEMENT field EMPTY>
<!ATTLIST field
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	childAccess (full | readOnly | none) #IMPLIED
	defaultValue CDATA #IMPLIED
>

<!ELEMENT contextElementSetDefinition (service | field)*>
<!ATTLIST contextElementSetDefinition
	name CDATA #REQUIRED
>

<!ELEMENT contextElementSet EMPTY>
<!ATTLIST contextElementSet
	contextElementSetDefName CDATA #REQUIRED
>

<!-- Formatter definitions -->

<!ELEMENT format EMPTY>
<!ATTLIST format
	fromName CDATA #IMPLIED
	fromValue CDATA #IMPLIED
	toName CDATA #REQUIRED
>

<!ELEMENT formatterDefinition (format* | param* | (inputFormatter, outputFormatter))>
<!ATTLIST formatterDefinition
	name CDATA #REQUIRED
	type (simple | custom | complex) #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT inputFormatter (format* | param*)>
<!ATTLIST inputFormatter
	type (simple | custom) #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT outputFormatter (format* | param*)>
<!ATTLIST outputFormatter
	type (simple | custom) #REQUIRED
	class CDATA #IMPLIED
>


<!-- ToolBar / Button definitions -->

<!ELEMENT button EMPTY>
<!ATTLIST button
	name CDATA #REQUIRED
	eventName CDATA #IMPLIED
	group CDATA #IMPLIED
	type (button | spacer) #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
	openWindowType (normal | dialog | popup | closeDialog | closePopup) #IMPLIED
	windowExtraParams CDATA #IMPLIED
	checkDirtyFlag (true | false) #IMPLIED
	checkWarnings (true | false) #IMPLIED
	checkDirtyModelIds CDATA #IMPLIED
	allowEventOnDirtyIds (true | false) #IMPLIED
	confirmMessageId CDATA #IMPLIED
	stateModelId CDATA #IMPLIED
	shortCutKey CDATA #IMPLIED
	authId CDATA #IMPLIED
>

<!ELEMENT buttonSet (button*)>
<!ATTLIST buttonSet
	name CDATA #REQUIRED
>

<!-- Service definitions -->

<!ELEMENT serviceDefinition (serviceMethod*)>
<!ATTLIST serviceDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	defaultMethodContext CDATA #IMPLIED
	validator CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
>

<!ELEMENT serviceMethod EMPTY>
<!ATTLIST serviceMethod
	name CDATA #REQUIRED
	executionMethod CDATA #REQUIRED
	context CDATA #IMPLIED
	validator CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
>

<!ELEMENT service (param*)>
<!ATTLIST service
	name CDATA #REQUIRED
	serviceDefName CDATA #REQUIRED
>

<!-- Operation definitions -->

<!ELEMENT operationDefinition EMPTY>
<!ATTLIST operationDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	context CDATA #IMPLIED
	validator CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
>


<!-- State definitions -->

<!ELEMENT state (subFlowData?, actionList*, entryActions?, transition*, exitActions?)>
<!ATTLIST state
	name CDATA #REQUIRED
	type (complex | simple | final) #REQUIRED
	initial (false | true) #IMPLIED
	page CDATA #IMPLIED
	activityName CDATA #IMPLIED
	context CDATA #IMPLIED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
	menu CDATA #IMPLIED
	validator CDATA #IMPLIED
	visible (true | false) #IMPLIED
	buttonSet CDATA #IMPLIED
	authId CDATA #IMPLIED
	waitingForEvent (true | false) #IMPLIED
	reachableByFlowOnly (true | false) #IMPLIED
>

<!ELEMENT subFlowData EMPTY>
<!ATTLIST subFlowData
	flowName CDATA #REQUIRED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
	goodFinalStates CDATA #IMPLIED
	formatContextOnInterrupt (false | true) #IMPLIED
>

<!ELEMENT actions (action*)>

<!ELEMENT validationExceptionActions (action*)>

<!ELEMENT validationAction (param*)>
<!ATTLIST validationAction
	refName CDATA #REQUIRED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
	stopOnError (true | false) #IMPLIED
>

<!ELEMENT validationActions (validationAction*)>

<!ELEMENT transition (actions?, validationExceptionActions?, validationActions?, subFlowData*)>
<!ATTLIST transition
	event CDATA #IMPLIED
	targetState CDATA #IMPLIED
	guard CDATA #IMPLIED
	customGuardName CDATA #IMPLIED
	validationGuard CDATA #IMPLIED
	internal (false | true) #IMPLIED
	default (true | false) #IMPLIED
	context CDATA #IMPLIED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
	validator CDATA #IMPLIED
	alternativeTargetState CDATA #IMPLIED
	handleValidationError (true | false) #IMPLIED
	traverseEvent (true | false) #IMPLIED
>

<!ELEMENT entryActions (action*)>

<!ELEMENT exitActions (action*)>

<!ELEMENT guardDefinition (param*)>
<!ATTLIST guardDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!ELEMENT activityDefinition (param*)>
<!ATTLIST activityDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	validator CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
>


<!-- Validation / Check definitions -->

<!ELEMENT validator (param | check | checkSet)*>
<!ATTLIST validator
	name CDATA #REQUIRED
	type (complex | custom) #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT validationCheckDefinition (checkParamDefinition*)>
<!ATTLIST validationCheckDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	method CDATA #REQUIRED
>

<!ELEMENT validationCheck (checkParam*)>
<!ATTLIST validationCheck
	name CDATA #REQUIRED
	validationCheckDef CDATA #REQUIRED
>

<!ELEMENT checkParam EMPTY>
<!ATTLIST checkParam
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	valueType CDATA #IMPLIED
	fieldName CDATA #IMPLIED
	caption CDATA #IMPLIED
	setFieldErrorState (true | false) #IMPLIED
>

<!ELEMENT validationCheckSet (check*)>
<!ATTLIST validationCheckSet
	name CDATA #IMPLIED
>

<!ELEMENT check (checkParam*)>
<!ATTLIST check
	validationCheckName CDATA #IMPLIED
	validationCheckDef CDATA #IMPLIED
	stopOnError (true | false) #IMPLIED
>

<!ELEMENT checkSet EMPTY>
<!ATTLIST checkSet
	validationCheckSetName CDATA #REQUIRED
>

<!ELEMENT checkParamDefinition EMPTY>
<!ATTLIST checkParamDefinition
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	defaultType CDATA #IMPLIED
	multiplicity CDATA #REQUIRED
>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/flower/fw/WorkFlowServices.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>

	<serviceDefinition name="WorkFlowSrv" class="com.ness.fw.shared.flower.workflow.WorkFlowFlowerService">
		<serviceMethod name="singleSignOnLogon" executionMethod="singleSignOnLogon" context="WFSingleSignOnLogonContext"/>
		<serviceMethod name="logon" executionMethod="logon" context="WFLogonContext"/>
		<serviceMethod name="logoff" executionMethod="logoff" context="WFEmptyContext"/>
		<serviceMethod name="exit" executionMethod="exit" context="WFEmptyContext"/>
		<serviceMethod name="retrieveTasks" executionMethod="retrieveTasks" context="WFRetrieveTasksContext"/>
		<serviceMethod name="getWorkItem" executionMethod="getWorkItem" context="WFGetWorkItemContext"/>
		<serviceMethod name="checkOut" executionMethod="checkOut" context="WFCheckOutContext"/>
		<serviceMethod name="checkIn" executionMethod="checkIn" context="WFCheckInContext"/>
		<serviceMethod name="cancelCheckOut" executionMethod="cancelCheckOut" context="WFCancelCheckOutContext"/>
		<serviceMethod name="postponeWorkItem" executionMethod="postponeWorkItem" context="WFPostponeWorkItemContext"/>
		<serviceMethod name="setPriorityOfProcessInstance" executionMethod="setPriorityOfProcessInstance" context="WFSetPriorityOfProcessInstanceContext"/>
		<serviceMethod name="setPriorityOfWorkItem" executionMethod="setPriorityOfWorkItem" context="WFSetPriorityOfWorkItemContext"/>
		<serviceMethod name="getProcessInstance" executionMethod="getProcessInstance" context="WFGetProcessInstanceContext"/>
		<serviceMethod name="getProcessInstanceByName" executionMethod="getProcessInstanceByName" context="WFGetProcessInstanceByNameContext"/>
		<serviceMethod name="returnWorkItemToGeneralQueue" executionMethod="returnWorkItemToGeneralQueue" context="WFReturnWorkItemToGeneralQueueContext"/>
		<serviceMethod name="retrieveProcesses" executionMethod="retrieveProcesses" context="WFRetrieveProcessesContext"/>
		<serviceMethod name="retrieveUsersForSelectSubstitute" executionMethod="retrieveUsersForSelectSubstitute" context="WFRetrieveUsersForSelectSubstituteContext"/>
		<serviceMethod name="routeWorkItem" executionMethod="routeWorkItem" context="WFRouteWorkItemContext"/>
		<serviceMethod name="retrieveUsersForWorkItemRouting" executionMethod="retrieveUsersForWorkItemRouting" context="WFRetrieveUsersForWorkItemRoutingContext"/>
		<serviceMethod name="setUserSubstitute" executionMethod="setUserSubstitute" context="WFSetUserSubstituteContext"/>
		<serviceMethod name="setCurrentUserSubstitute" executionMethod="setCurrentUserSubstitute" context="WFSetCurrentUserSubstituteContext"/>
		<serviceMethod name="getUserSubstitute" executionMethod="getUserSubstitute" context="WFGetUserSubstituteContext"/>
		<serviceMethod name="getCurrentUserSubstitute" executionMethod="getCurrentUserSubstitute" context="WFGetCurrentUserSubstituteContext"/>
		<serviceMethod name="terminateProcess" executionMethod="terminateProcess" context="WFTerminateProcessContext"/>
		<serviceMethod name="doesProcessInstanceHaveCheckedOutItems" executionMethod="doesProcessInstanceHaveCheckedOutItems" context="WFDoesProcessInstanceHaveCheckedOutItemsContext"/>
		<serviceMethod name="setUserAsAbsent" executionMethod="setUserAsAbsent" context="WFSetUserAsAbsentContext"/>
		<serviceMethod name="isAbsent" executionMethod="isAbsent" context="WFIsAbsentContext"/>
		<serviceMethod name="retrieveFilterNames" executionMethod="retrieveFilterNames" context="WFRetrieveFilterNamesContext"/>
		<serviceMethod name="getProcessTemplateNames" executionMethod="getProcessTemplateNames" context="WFGetProcessTemplateNamesContext"/>
		<serviceMethod name="retrieveUsersInOrganizationalTeam" executionMethod="retrieveUsersInOrganizationalTeam" context="WFRetrieveUsersInOrganizationalTeamContext"/>
		<serviceMethod name="getCustomerOpenProcesses" executionMethod="getCustomerOpenProcesses" context="WFGetCustomerOpenProcessesContext"/>
		<serviceMethod name="doesCustomerHaveOpenProcesses" executionMethod="doesCustomerHaveOpenProcesses" context="WFDoesCustomerHaveOpenProcessesContext"/>
		<serviceMethod name="getListOfCustomerOpenProcesses" executionMethod="getListOfCustomerOpenProcesses" context="WFGetListOfCustomerOpenProcessesContext"/>
		<serviceMethod name="autoOpeningOfNextWorkItem" executionMethod="autoOpeningOfNextWorkItem" context="WFAutoOpeningOfNextWorkItemContext"/>
		<serviceMethod name="alertForAutoOpeningOfNextWorkItem" executionMethod="alertForAutoOpeningOfNextWorkItem" context="WFAlertForAutoOpeningOfNextWorkItemContext"/>
		<serviceMethod name="prepareListOfUsers" executionMethod="prepareListOfUsers" context="WFPrepareListOfUsersContext"/>
		<serviceMethod name="forceRestart" executionMethod="forceRestart" context="WFForceRestartContext"/>
		<serviceMethod name="getLastPerformedActivity" executionMethod="getLastPerformedActivity" context="WFGetLastPerformedActivityContext"/>
		<serviceMethod name="retrievePeopleThisUserIsAuthorizedFor" executionMethod="retrievePeopleThisUserIsAuthorizedFor" context="WFRetrievePeopleThisUserIsAuthorizedForContext"/>
		<serviceMethod name="createAndStartProcessInstance" executionMethod="createAndStartProcessInstance" context="WFCreateAndStartProcessInstanceContext"/>
		<serviceMethod name="getLastHandlerOfCustomer" executionMethod="getLastHandlerOfCustomer" context="WFGetLastHandlerOfCustomerContext"/>
	</serviceDefinition>


</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/flower/app/pilot/agreement/flows/searchAgreement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>	

	<flow name="serachAgreementFlow" context="searchAgreementCTX" menu="agreementMenu">	
		<state name="initState" type="simple" initial="true">
			<transition default="true" targetState="viewState">
				<actions>
			   		<action type="operation" refName="PLInitSearchAgreementOP"/>
					<action type="operation" refName="ClearDirtyFlagOp"/>
				</actions>					
			</transition>
 		</state> 
 		
		<state name="viewState" type="complex" page="app/agreement/jsp/searchAgreement.jsp" buttonSet="searchHeskemButtons,pagingBS">				
			
			<actionList name="searchAL">
                <action type="operation" refName="PLFillAgreementSearchResultsOP"/>
				<action refName="SetButtonsPagingState" type="operation"></action>
			</actionList>
			
			<transition internal="true" event="search">
				<actions>
					<action type="actionList" refName="searchAL" />
		        </actions>
		    </transition>
	
			<transition event="searchResultTableModel|sort" internal="true"/>
			<transition event="searchResultTableModel|order" internal="true"/>

			<transition event="searchResultTableModel|link1" targetState="agreementDetailsState" outFormatter="agreementUpdateModeFMT">
				<actions>
					<action type="operation" refName="PLGetMenuAgreementIdOP"></action>
				</actions>
			</transition>
	
			<transition event="searchResultTableModel|link2" targetState="agreementDetailsState" outFormatter="agreementCopyModeFMT">
				<actions>
					<action type="operation" refName="PLGetMenuAgreementIdOP"></action>
				</actions>
			</transition>
	
			<transition internal="true" event="clearFields">
				<actions>
					<action type="operation" refName="PLClearAgreementCriteriaOP"></action>
				</actions>
			</transition> 
										
	 		<transition event="searchResultTableModel|link" targetState="agreementDetailsState" outFormatter="agreementUpdateModeFMT">
	 			<actions>
					<action type="operation" refName="PLGetLinkAgreementIdOP"></action>
				</actions>	 			
	 		</transition>
	
			<!-- start handling paging -->
			<transition event="first" internal="true">
				<actions>
					<action refName="PLGetAgreementsPage" type="operation">
						<param name="operationType" class="java.lang.Integer" value="0"/>
					</action>
					<action refName="SetButtonsPagingState" type="operation"></action>
				</actions>
			</transition>
			
			<transition event="last" internal="true">
				<actions>
					<action refName="PLGetAgreementsPage" type="operation">
						<param name="operationType" class="java.lang.Integer" value="1"/>
					</action>
					<action refName="SetButtonsPagingState" type="operation"></action>
				</actions>
			</transition>
			
			<transition event="next" internal="true">
				<actions>
					<action refName="PLGetAgreementsPage" type="operation">
						<param name="operationType" class="java.lang.Integer" value="2"/>
					</action>
					<action refName="SetButtonsPagingState" type="operation"/>
				</actions>
			</transition>
						
			<transition event="prev" internal="true">
				<actions>
					<action refName="PLGetAgreementsPage" type="operation">
						<param name="operationType" class="java.lang.Integer" value="3"/>
					</action>
					<action refName="SetButtonsPagingState" type="operation"/>
				</actions>
			</transition>		
			<!-- end handling paging -->

			<transition event="new" targetState="agreementDetailsState" outFormatter="agreementNewModeFMT"/>
			<transition event="delete" targetState="viewState" >
				<actions>
					<action type="operation" refName="deleteAgreementOp"/>
					<action type="actionList" refName="searchAL" />
				</actions>
			</transition>
			<transition event="close" targetState="finalScreen"/>										
		</state>
		
		<state name="agreementDetailsState" type="complex">
			<subFlowData flowName="buildAgreementFlow" inFormatter="agreementIdFMT"/>		
				<transition event="finalScreen" targetState="viewState"></transition>							
		</state>  
				
		<state name="finalScreen" type="final" />	
	</flow>
	
	<operationDefinition name="deleteAgreementOp" class="fwpilot.agreement.operations.PLDeleteAgreementOP"/>
	
</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/flower/app/pilot/customer/contexts/buildCustomer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>

	<context name="pirteyCustomerContext">

		<field name="custID" type="string"  />
		<field name="title" type="xiString"  />
		<field name="customer" type="fwpilot.customer.vo.Customer"  />
		<field name="customerTypeModel" type="listModel"  />

		<field name="customerType" type="integer" childAccess="full" />

		<field name="customerStatusModel" type="listModel"  />	
		<field name="customerSexModel" type="listModel"  />
		<field name="customerSmokingModel" type="listModel"  />
		<field name="customerProfessionModel" type="listModel"  />
	
		<!--TABS field-->
			
		<!--general-->
		<field name="identification" type="xiInteger" childAccess="full"/>
		<field name="firstName" type="xiString" childAccess="full"/>
		<field name="lastName" type="xiString" childAccess="full"/>
		<field name="englishFirstName" type="xiString" childAccess="full"/>
		<field name="englishLastName" type="xiString" childAccess="full"/>
		<field name="birthDate" type="xiDate" childAccess="full"/>
		<field name="telephone" type="xiInteger" childAccess="full"/>
		<field name="fax" type="xiInteger" childAccess="full"/>
		<field name="mobilePhone" type="xiInteger" childAccess="full"/>
		<field name="numberOfChilds" type="xiInteger" childAccess="full"/>
	
		<!--address-->
		<field name="addressTableModel" type="tableModel" childAccess="full"/>
		<field name="addressMainModel" type="listModel"  />
		<field name="city" type="xiString" childAccess="full"/>
		<field name="street" type="xiString" childAccess="full"/>
		<field name="streetNumber" type="xiInteger" childAccess="full"/>
		<field name="addressTelephone" type="xiInteger" childAccess="full"/>
		<field name="addressFax" type="xiInteger" childAccess="full"/>

		<!--related-->
		<field name="relatedIdentification" type="xiInteger"  />
		<field name="relatedFirstName" type="xiString" childAccess="full"/>
		<field name="relatedLastName" type="xiString" childAccess="full"/>
		<field name="relatedBirthDate" type="xiDate" childAccess="full"/>
		<field name="relatedTableModel" type="tableModel" childAccess="full"/>
		<field name="customerRelatedTypeModel" type="listModel"  />
		<field name="relatedSexModel" type="listModel"  />

	</context>
</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/flower/app/pilot/customer/operations/buildCustomerOP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>
    <operationDefinition name="PLInitBuildCustomerOP"  activityType="readOnly" class="fwpilot.customer.operations.PLInitBuildCustomerOP"/>
    <operationDefinition name="PLSaveCustomerOP"  activityType="readWrite"  class="fwpilot.customer.operations.PLSaveCustomerOP"/>
	<operationDefinition name="PLInitAddressOP"  activityType="readOnly" class="fwpilot.customer.operations.PLInitAddressOP"/>
	<operationDefinition name="PLNewAddressOP"  activityType="readWrite" class="fwpilot.customer.operations.PLNewAddressOP"/>
	<operationDefinition name="PLUpdateAddressOP"  activityType="readWrite" class="fwpilot.customer.operations.PLUpdateAddressOP"/>
	<operationDefinition name="PLDeleteAddressOP"  activityType="readWrite" class="fwpilot.customer.operations.PLDeleteAddressOP"/>
	<operationDefinition name="clickAddress"  activityType="readOnly" class="fwpilot.customer.operations.PLLoadAddressOP"/>
	<operationDefinition name="PLInitRelatedOP"  activityType="readOnly" class="fwpilot.customer.operations.PLInitRelatedOP"/>
	<operationDefinition name="PLNewRelatedOP"  activityType="readWrite" class="fwpilot.customer.operations.PLNewRelatedOP"/>
	<operationDefinition name="PLUpdateRelatedOP"  activityType="readWrite" class="fwpilot.customer.operations.PLUpdateRelatedOP"/>
	<operationDefinition name="PLDeleteRelatedOP"  activityType="readWrite" class="fwpilot.customer.operations.PLDeleteRelatedOP"/>
	<operationDefinition name="clickRelated"  activityType="readOnly" class="fwpilot.customer.operations.PLLoadRelatedOP"/>

	<operationDefinition name="initSearchCustomerFromAgreement"  activityType="readOnly"  class="fwpilot.customer.operations.PLCustomerSearchInitFromAgreementOP"/>
	<operationDefinition name="validateCustomer"  activityType="readOnly" context="validateCustomerContext" class="fwpilot.customer.operations.ValidateCustomerSearch"/>
	<operationDefinition name="fillCustomerFromAgreementSearchResults"  activityType="readOnly"  class="fwpilot.customer.operations.FillCustomerFromAgreementSearchResults"/>


</root>
