=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/dtd/flower.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by aa (aa) -->
<!--DTD generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->

<!-- Root elements -->

<!ELEMENT root (validationCheckDefinition | validationCheck | validationCheckSet | buttonSet | flowImplementations | validator | guardDefinition | structureDefinition | typeDefinition | context | contextElementSetDefinition | operationDefinition | serviceDefinition | activityDefinition | flow | formatterDefinition)*>

<!-- Generic elements -->

<!ELEMENT param EMPTY>
<!ATTLIST param
	name CDATA #REQUIRED
	value CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!ELEMENT implementation EMPTY>
<!ATTLIST implementation
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>


<!-- Flow definitions -->

<!ELEMENT flowImplementations (implementation*)>

<!ELEMENT flow (tabSystemData?, actionList*, state+)>
<!ATTLIST flow
	name CDATA #REQUIRED
	context CDATA #IMPLIED
	independent (true | false) #IMPLIED
	menu CDATA #IMPLIED
	defaultInternalTransitions (true | false) #IMPLIED
	validator CDATA #IMPLIED
	type (tabSystem | generic) #IMPLIED
	implementation CDATA  #IMPLIED
	authId CDATA #IMPLIED
>

<!ELEMENT tabSystemData EMPTY>
<!ATTLIST tabSystemData
	page CDATA #REQUIRED
>


<!-- Action definitions -->

<!ELEMENT action (param*)>
<!ATTLIST action
	type (operation | actionList | service) #REQUIRED
	refName CDATA #REQUIRED
	methodName CDATA #IMPLIED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
>

<!ELEMENT actionList (action*)>
<!ATTLIST actionList
	name CDATA #REQUIRED
>

<!-- Type Definition definitions -->

<!ELEMENT builderTypeDefinition (param*)>
<!ATTLIST builderTypeDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!ELEMENT builder EMPTY>
<!ATTLIST builder
	fromType CDATA #IMPLIED
	builderTypeName CDATA #IMPLIED
	method CDATA #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT printer EMPTY>
<!ATTLIST printer
	builderTypeName CDATA #IMPLIED
	method CDATA #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT builders (builder+)>

<!ELEMENT type (builders?, printer?)>
<!ATTLIST type
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	xiType (true | false) #IMPLIED
	basicXIType CDATA #IMPLIED
>

<!ELEMENT typeDefinition (type | builderTypeDefinition)*>

<!-- Structure definitions -->

<!ELEMENT structureField EMPTY>
<!ATTLIST structureField
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	defaultValue CDATA #IMPLIED
>

<!ELEMENT structureDefinition (structureField*)>
<!ATTLIST structureDefinition
	name CDATA #REQUIRED
>


<!-- Context definitions -->

<!ELEMENT context (service | field | contextElementSet)*>
<!ATTLIST context
	name CDATA #REQUIRED
	type (dynamic | static) #IMPLIED
	parent CDATA #IMPLIED
	addOnDemand (true | false) #IMPLIED
>

<!ELEMENT field EMPTY>
<!ATTLIST field
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	childAccess (full | readOnly | none) #IMPLIED
	defaultValue CDATA #IMPLIED
>

<!ELEMENT contextElementSetDefinition (service | field)*>
<!ATTLIST contextElementSetDefinition
	name CDATA #REQUIRED
>

<!ELEMENT contextElementSet EMPTY>
<!ATTLIST contextElementSet
	contextElementSetDefName CDATA #REQUIRED
>

<!-- Formatter definitions -->

<!ELEMENT format EMPTY>
<!ATTLIST format
	fromName CDATA #IMPLIED
	fromValue CDATA #IMPLIED
	toName CDATA #REQUIRED
>

<!ELEMENT formatterDefinition (format* | param* | (inputFormatter, outputFormatter))>
<!ATTLIST formatterDefinition
	name CDATA #REQUIRED
	type (simple | custom | complex) #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT inputFormatter (format* | param*)>
<!ATTLIST inputFormatter
	type (simple | custom) #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT outputFormatter (format* | param*)>
<!ATTLIST outputFormatter
	type (simple | custom) #REQUIRED
	class CDATA #IMPLIED
>


<!-- ToolBar / Button definitions -->

<!ELEMENT button EMPTY>
<!ATTLIST button
	name CDATA #REQUIRED
	eventName CDATA #IMPLIED
	group CDATA #IMPLIED
	type (button | spacer) #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
	openWindowType (normal | dialog | popup | closeDialog | closePopup) #IMPLIED
	windowExtraParams CDATA #IMPLIED
	checkDirtyFlag (true | false) #IMPLIED
	checkWarnings (true | false) #IMPLIED
	checkDirtyModelIds CDATA #IMPLIED
	allowEventOnDirtyIds (true | false) #IMPLIED
	confirmMessageId CDATA #IMPLIED
	stateModelId CDATA #IMPLIED
	shortCutKey CDATA #IMPLIED
	authId CDATA #IMPLIED
>

<!ELEMENT buttonSet (button*)>
<!ATTLIST buttonSet
	name CDATA #REQUIRED
>

<!-- Service definitions -->

<!ELEMENT serviceDefinition (serviceMethod*)>
<!ATTLIST serviceDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	defaultMethodContext CDATA #IMPLIED
	validator CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
>

<!ELEMENT serviceMethod EMPTY>
<!ATTLIST serviceMethod
	name CDATA #REQUIRED
	executionMethod CDATA #REQUIRED
	context CDATA #IMPLIED
	validator CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
>

<!ELEMENT service (param*)>
<!ATTLIST service
	name CDATA #REQUIRED
	serviceDefName CDATA #REQUIRED
>

<!-- Operation definitions -->

<!ELEMENT operationDefinition EMPTY>
<!ATTLIST operationDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	context CDATA #IMPLIED
	validator CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
>


<!-- State definitions -->

<!ELEMENT state (subFlowData?, actionList*, entryActions?, transition*, exitActions?)>
<!ATTLIST state
	name CDATA #REQUIRED
	type (complex | simple | final) #REQUIRED
	initial (false | true) #IMPLIED
	page CDATA #IMPLIED
	activityName CDATA #IMPLIED
	context CDATA #IMPLIED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
	menu CDATA #IMPLIED
	validator CDATA #IMPLIED
	visible (true | false) #IMPLIED
	buttonSet CDATA #IMPLIED
	authId CDATA #IMPLIED
	waitingForEvent (true | false) #IMPLIED
	reachableByFlowOnly (true | false) #IMPLIED
>

<!ELEMENT subFlowData EMPTY>
<!ATTLIST subFlowData
	flowName CDATA #REQUIRED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
	goodFinalStates CDATA #IMPLIED
	formatContextOnInterrupt (false | true) #IMPLIED
>

<!ELEMENT actions (action*)>

<!ELEMENT validationExceptionActions (action*)>

<!ELEMENT validationAction (param*)>
<!ATTLIST validationAction
	refName CDATA #REQUIRED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
	stopOnError (true | false) #IMPLIED
>

<!ELEMENT validationActions (validationAction*)>

<!ELEMENT transition (actions?, validationExceptionActions?, validationActions?, subFlowData*)>
<!ATTLIST transition
	event CDATA #IMPLIED
	targetState CDATA #IMPLIED
	guard CDATA #IMPLIED
	customGuardName CDATA #IMPLIED
	validationGuard CDATA #IMPLIED
	internal (false | true) #IMPLIED
	default (true | false) #IMPLIED
	context CDATA #IMPLIED
	inFormatter CDATA #IMPLIED
	outFormatter CDATA #IMPLIED
	complexFormatter CDATA #IMPLIED
	validator CDATA #IMPLIED
	alternativeTargetState CDATA #IMPLIED
	handleValidationError (true | false) #IMPLIED
	traverseEvent (true | false) #IMPLIED
>

<!ELEMENT entryActions (action*)>

<!ELEMENT exitActions (action*)>

<!ELEMENT guardDefinition (param*)>
<!ATTLIST guardDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
>

<!ELEMENT activityDefinition (param*)>
<!ATTLIST activityDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	validator CDATA #IMPLIED
	activityType (readWrite | readOnly) #IMPLIED
>


<!-- Validation / Check definitions -->

<!ELEMENT validator (param | check | checkSet)*>
<!ATTLIST validator
	name CDATA #REQUIRED
	type (complex | custom) #REQUIRED
	class CDATA #IMPLIED
>

<!ELEMENT validationCheckDefinition (checkParamDefinition*)>
<!ATTLIST validationCheckDefinition
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	method CDATA #REQUIRED
>

<!ELEMENT validationCheck (checkParam*)>
<!ATTLIST validationCheck
	name CDATA #REQUIRED
	validationCheckDef CDATA #REQUIRED
>

<!ELEMENT checkParam EMPTY>
<!ATTLIST checkParam
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	valueType CDATA #IMPLIED
	fieldName CDATA #IMPLIED
	caption CDATA #IMPLIED
	setFieldErrorState (true | false) #IMPLIED
>

<!ELEMENT validationCheckSet (check*)>
<!ATTLIST validationCheckSet
	name CDATA #IMPLIED
>

<!ELEMENT check (checkParam*)>
<!ATTLIST check
	validationCheckName CDATA #IMPLIED
	validationCheckDef CDATA #IMPLIED
	stopOnError (true | false) #IMPLIED
>

<!ELEMENT checkSet EMPTY>
<!ATTLIST checkSet
	validationCheckSetName CDATA #REQUIRED
>

<!ELEMENT checkParamDefinition EMPTY>
<!ATTLIST checkParamDefinition
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	defaultType CDATA #IMPLIED
	multiplicity CDATA #REQUIRED
>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/flower/app/pilot/customer/contexts/searchCustomer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>
	<buttonSet name="searchCustomerButtons">
		<button name="close" eventName="close" group="left"/>
	</buttonSet>

	<context name="chooseCustomerContext">	
		<field name="customerTypeModel" type="listModel"  />
		<field name="customerType" type="integer"  />
	</context>

	<context name="fillResultContext" addOnDemand="true" ></context>

	<context name="searchCustomerContext">	

		<!-- search fields -->
		<field name="searchResultTableModel" type="tableModel"  />
		<field name="customerTypeModel" type="listModel"  />
		<field name="id" type="xiInteger"  />
		<field name="firstName" type="xiString"  />
		<field name="telephone" type="xiString"  />
		<field name="city" type="xiString"  />

		<!-- seleced id from table-->
		<field name="custID" type="string"  />		

		<!-- selected customer type -->
		<field name="selectedCustomerTypeModel" type="listModel"  />
		<field name="selectedType" type="integer"  />

		<!-- ??? check if necesssary -->
		<field name="customerId" type="xiInteger" childAccess="full"/>
		<field name="customerName" type="xiString" childAccess="full"/>			

		<field name="pagingService" type="com.ness.fw.persistence.PagingService"/>

	</context>
</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/flower/app/pilot/agreement/operations/operations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>

	<operationDefinition name="PLInitSearchAgreementOP"  activityType="readOnly" class="fwpilot.agreement.operations.PLInitSearchAgreementOP"/>
    <operationDefinition name="PLFillAgreementSearchResultsOP" activityType="readOnly"  class="fwpilot.agreement.operations.PLFillAgreementSearchResults"/>
    <operationDefinition name="PLClearAgreementCriteriaOP" activityType="readOnly" class="fwpilot.agreement.operations.PLClearAgreementCriteriaOP"/>
    <operationDefinition name="PLGetLinkAgreementIdOP" activityType="readOnly" class="fwpilot.agreement.operations.PLGetLinkAgreementIdOP"/>
    <operationDefinition name="PLGetMenuAgreementIdOP" activityType="readOnly" class="fwpilot.agreement.operations.PLGetMenuAgreementIdOP"/>
    <operationDefinition name="PLGetAgreementsPage" activityType="readOnly" class="fwpilot.agreement.operations.PLAgreementGetPage"/>
    <operationDefinition name="resetTabModel" activityType="readOnly" class="fwpilot.agreement.operations.PLResetTabModel"/>

 
 
 	<!-- pacakges & programs operations-->
 	<operationDefinition name="PLInitPackageOP"  activityType="readOnly" class="fwpilot.agreement.operations.PLInitPackageOP"/>
    <operationDefinition name="PLInitProgramOP"  activityType="readOnly" class="fwpilot.agreement.operations.PLInitProgramOP"/>


 	<!-- Documents tab operations-->
 	<operationDefinition name="PLInitAgreement"  activityType="readOnly" class="fwpilot.agreement.operations.PLInitAgreement"/>
    <operationDefinition name="PLInitGeneralTab"  activityType="readOnly" class="fwpilot.agreement.operations.PLInitGeneralTab"/>
	<operationDefinition name="PLInitDocumentsOP"  activityType="readOnly" class="fwpilot.agreement.operations.PLInitDocumentsOP"/>
	<operationDefinition name="PLNewDocumentOP"  class="fwpilot.agreement.operations.PLNewDocumentOP"/>
	<operationDefinition name="PLUpdateDocumentOP"   class="fwpilot.agreement.operations.PLUpdateDocumentOP"/>
	<operationDefinition name="PLDeleteDocumentOP"   class="fwpilot.agreement.operations.PLDeleteDocumentOP"/>
	<operationDefinition name="PLDeleteAllDocumentOP"   class="fwpilot.agreement.operations.PLDeleteAllDocumentOP"/>
	<operationDefinition name="PLDocumentsLoadOP"  activityType="readOnly" class="fwpilot.agreement.operations.PLDocumentsLoadOP"/>
    <operationDefinition name="PLDeletePackageOP"   class="fwpilot.agreement.operations.PLDeletePackageOP"/>
    <operationDefinition name="PLSaveAgreementOP"   class="fwpilot.agreement.operations.PLSaveAgreementOP"/>
    <operationDefinition name="PLFillCatalogOP"  activityType="readOnly" class="fwpilot.agreement.operations.PLFillCatalogOP"/>
    <operationDefinition name="PLAddPackageOP"   class="fwpilot.agreement.operations.PLAddPackageOP"/>
    <operationDefinition name="checkExistance"  activityType="readOnly" class="fwpilot.customer.operations.CheckCustomerExistance"/>
</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/flower/fw/WorkFlowDataTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>

	<!-- ======================================== -->
	<!-- Data Bulders and Data Types Declarations -->
	<!-- ======================================== -->

	<typeDefinition>
		<!-- UserCredentials type -->
		<type name="WFUserCredentials" class="com.ness.fw.workflow.UserCredentials"/>
	</typeDefinition>

	<typeDefinition>
		<!-- Agent type -->
		<type name="WFAgent" class="com.ness.fw.workflow.Agent"/>
	</typeDefinition>

	<typeDefinition>
		<!-- WorkFlowServiceParameterMap type -->
		<type name="WFParametersMap" class="com.ness.fw.workflow.WorkFlowServiceParameterMap"/>
	</typeDefinition>

	<typeDefinition>
		<!-- WFWorkList type -->
		<type name="WFWorkList" class="com.ness.fw.workflow.WFWorkList"/>
	</typeDefinition>

	<typeDefinition>
		<!-- WFWorkItemList type -->
		<type name="WFWorkItemList" class="com.ness.fw.workflow.WFWorkItemList"/>
	</typeDefinition>

	<typeDefinition>
		<!-- WFWorkItem type -->
		<type name="WFWorkItem" class="com.ness.fw.workflow.WFWorkItem"/>
	</typeDefinition>

	<typeDefinition>
		<!-- WFProcessInstance type -->
		<type name="WFProcessInstance" class="com.ness.fw.workflow.WFProcessInstance"/>
	</typeDefinition>

	<typeDefinition>
		<!-- WFProcessInstanceList type -->
		<type name="WFProcessInstanceList" class="com.ness.fw.workflow.WFProcessInstanceList"/>
	</typeDefinition>

	<typeDefinition>
		<!-- WFLastHandlerOfCustomer type -->
		<type name="WFLastHandlerOfCustomer" class="com.ness.fw.workflow.WFLastHandlerOfCustomer"/>
	</typeDefinition>

</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/flower/app/pilot/customer/formatters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>
	<formatterDefinition name="customerTypeFormatter" type="simple">
		<format fromName="selectedCustomerTypeModel" toName="customerTypeModel" />
		<format fromName="selectedType" toName="customerType" />
		<format fromName="custID" toName="custID" />
	</formatterDefinition>

	<formatterDefinition name="customerTypeInFormatter" type="simple">
		<format fromName="customerTypeModel" toName="customerTypeModel" />
	</formatterDefinition>

	<formatterDefinition name="customerTypeOutFormatter" type="simple">
		<format fromName="customerTypeModel" toName="selectedCustomerTypeModel" />
		<format fromName="customerType" toName="selectedType" />
	</formatterDefinition>
</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/flower/app/pilot/customer/flows/searchCustomer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>		
	<flow name="searchCustomerFlow" context="searchCustomerContext">	
		<state name="initState" type="simple" initial="true">
			<transition default="true" targetState="viewState">
				<actions>
			   		<action type="operation" refName="initSearchCustomer"/>	
				</actions>					
			</transition>
 		</state> 
 
		<state name="viewState" type="complex" page="app/customer/jsp/searchCustomer.jsp" buttonSet="searchCustomerButtons">			
			<transition internal="true" event="search">
				<actions>
                    <action type="operation" refName="PLFillCustomerSearchResultsOP"/>
					<action refName="PLSetCustomerButtonsPagingState" type="operation"/>
		        </actions>
		    </transition>	

			<transition internal="true" event="clearFields">
				<actions>
					<action type="operation" refName="clearSearchCustomerFields"></action>
				</actions>
			</transition> 
					
			<transition event="searchResultTableModel|sort" internal="true"/>
			<transition event="searchResultTableModel|order" internal="true"/>

			<transition event="searchResultTableModel|link" targetState="customerDetailsState">
				<actions>
					<action type="operation" refName="PLLoadCustomerIdOP"></action>
				</actions>
			</transition>
						
			<transition event="new" internal="true">
				<subFlowData flowName="chooseCustomerFlow" inFormatter="customerTypeInFormatter" outFormatter="customerTypeOutFormatter" goodFinalStates="okClick"></subFlowData>				
			</transition>

			<!-- handling the return from the choose customer -->
			<transition event="okClick" targetState="customerDetailsState"></transition>
			<transition event="cancelClick" internal="true"></transition>
			<transition event="close" targetState="finalScreen"></transition>										

			<!-- start handling paging -->
			<transition event="searchResultTableModel|first" internal="true">
				<actions>
					<action refName="PLCustomersGetPage" type="operation"/>
					<action refName="PLSetCustomerButtonsPagingState" type="operation"></action>
				</actions> 
			</transition>
			
			<transition event="searchResultTableModel|last" internal="true">
				<actions>
					<action refName="PLCustomersGetPage" type="operation"/>
					<action refName="PLSetCustomerButtonsPagingState" type="operation"></action>
				</actions> 
			</transition>
			
			<transition event="searchResultTableModel|next" internal="true">
				<actions>
					<action refName="PLCustomersGetPage" type="operation"/>
					<action refName="PLSetCustomerButtonsPagingState" type="operation"/>
				</actions> 
			</transition>
						
			<transition event="searchResultTableModel|prev" internal="true">
				<actions>
					<action refName="PLCustomersGetPage" type="operation"/>
					<action refName="PLSetCustomerButtonsPagingState" type="operation"/>
				</actions> 
			</transition>		

			<transition event="searchResultTableModel|specificPage" internal="true">
				<actions>
					<action refName="PLCustomersGetPage" type="operation"/>
					<action refName="PLSetCustomerButtonsPagingState" type="operation"/>
				</actions> 
			</transition>		



			<!-- end handling paging -->
		</state>
		
		<state name="finalScreen" type="final" />
		
		<state name="customerDetailsState" type="complex">
			<subFlowData flowName="buildCustomerFlow" inFormatter="customerTypeFormatter"/>		

			<transition event="finalScreen" targetState="initState"></transition>
		</state>  
						
					
	</flow>
		
	<flow name="chooseCustomerFlow" context="chooseCustomerContext" independent="true">
		<state name="initPage" initial="true" type="complex" page="app/customer/jsp/chooseCustomer.jsp">
			<transition targetState="okClick" event="ok" >
				<actions>
					<action refName="newCustomer" type="operation"/>
				</actions>
			</transition>
			<transition event="cancel" targetState="cancelClick" />
		</state>
		
		<state name="okClick" type="final"/>		
		<state name="cancelClick" type="final"/>
	</flow>					
</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/flower/app/pilot/agreement/formatters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>
	<formatterDefinition name="agreementIdFMT" type="simple">
		<format fromName="selectedAgreementID" toName="agreementId" />
		<format fromName="mode" toName="mode" />			
	</formatterDefinition>

	<formatterDefinition name="agreementNewModeFMT" type="simple">
		<format fromValue="new" toName="mode"/>
	</formatterDefinition>

	<formatterDefinition name="agreementCopyModeFMT" type="simple">
		<format fromValue="copy" toName="mode"/>
	</formatterDefinition>

	<formatterDefinition name="agreementUpdateModeFMT" type="simple">
		<format fromValue="update" toName="mode"/>
	</formatterDefinition>

	<formatterDefinition name="customerFormatter" type="simple">
		<format fromName="customerId" toName="id"/>
		<format fromName="customerName" toName="firstName"/>				
	</formatterDefinition>

	<formatterDefinition name="custIDFormmater" type="simple">
		<format fromName="customerId" toName="custID"/>
	</formatterDefinition>


	<formatterDefinition name="customerOutFormatter" type="simple">
		<format fromName="customerId" toName="customerId"/>
		<format fromName="customerName" toName="customerName"/>				
	</formatterDefinition>



</root>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/flower/app/pilot/agreement/contexts/building.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "flower.dtd">
<root>

	<context name="AgreementCTX">
	
		<!-- will be format to the customerFlow when clicking the link -->
		<field name="custID" type="integer" childAccess="full"/>

		<!-- the choosen package from the catalog -->
		<field name="selectedPackage" type="xiInteger" childAccess="full"/>		
		<field name="addedPackage" type="fwpilot.agreement.vo.AgreementPackage" childAccess="full"/>
		<field name="addedPackageNodeId" type="xiString" childAccess="full"/>


		<!-- ======================================== -->
		<!-- General Agreeemnt fields -->
		<!-- ======================================== -->
		<field name="agreementId" type="xiInteger" childAccess="full"/>
		<field name="agreement" type="fwpilot.agreement.vo.Agreement" childAccess="full"/>
		<field name="title" type="xiString" childAccess="full"/>
		<field name="mode" type="xiString" childAccess="full"/>
		<field name="agreementDisplayStateModel" type="displayStateModel" childAccess="full"/>
		<field name="customerLinkModel" type="buttonModel" childAccess="full" />


		<!-- ======================================== -->
		<!-- Agreeemnt Details fields -->
		<!-- ======================================== -->
		<field name="agreementDetailsTreeModel" type="treeModel" childAccess="readOnly"/>
		<field name="catalogTableModel" type="treeModel" childAccess="readOnly"/>
		<field name="name" type="xiString" childAccess="readOnly"/>
		<field name="description" type="xiString" childAccess="readOnly"/>
		<field name="identification" type="xiInteger" childAccess="readOnly"/>
		<field name="startDate" type="xiDate" childAccess="readOnly"/>
		<field name="endDate" type="xiDate" childAccess="readOnly"/>
		<field name="minimalPeriod" type="xiInteger" childAccess="readOnly"/>
		<field name="minimalPeriodTextModel" type="textModel" childAccess="readOnly"/>
		<field name="statusModel" type="listModel" childAccess="readOnly"/>
		<field name="automaticCheckBoxModel" type="listModel" childAccess="readOnly"/>
		<field name="canBeCanceledCheckBoxModel" type="listModel" childAccess="readOnly"/>
		<field name="agreementTypeModel" type="listModel" childAccess="readOnly"/>
		<field name="customerTypeModel" type="listModel" childAccess="readOnly"/>
		<field name="deleteModel" type="buttonModel" childAccess="readOnly"/>

		<!-- temporary patch. inorder to support dialog errors-->
		<field name="customerId" type="xiString" childAccess="readOnly"/>
		<field name="customerName" type="xiString" childAccess="readOnly"/>


		<!-- ======================================== -->
		<!-- Attributes tab fields -->
		<!-- ======================================== -->
		
		<field name="generalTabModel" type="tabModel"/>
		
		<field name="attributesModel" type="listModel" childAccess="full"/>


		<!-- ======================================== -->
		<!-- Program tab fields -->
		<!-- ======================================== -->
		<field name="progId" type="xiInteger" childAccess="readOnly"/>
		<field name="progName" type="xiString" childAccess="readOnly"/>
		<field name="progMinimalStartAge" type="xiInteger" childAccess="readOnly"/>
		<field name="progMaximalStartAge" type="xiInteger" childAccess="readOnly"/>
		<field name="progEndAge" type="xiInteger" childAccess="readOnly"/>
		<field name="progDescription" type="xiString" childAccess="readOnly"/>

		<!-- ======================================== -->
		<!-- Package tab fields -->
		<!-- ======================================== -->
		<field name="packId" type="xiInteger" childAccess="readOnly"/>
		<field name="packName" type="xiString" childAccess="readOnly"/>
		<field name="packMinimalStartAge" type="xiInteger" childAccess="readOnly"/>
		<field name="packMaximalStartAge" type="xiInteger" childAccess="readOnly"/>
		<field name="packEndAge" type="xiInteger" childAccess="readOnly"/>
		<field name="packDescription" type="xiString" childAccess="readOnly"/>
		<field name="packType" type="xiInteger" childAccess="readOnly"/>
		<field name="packInsuranceSum" type="xiDouble" childAccess="readOnly"/>
		<field name="packAfterDiscount" type="xiDouble" childAccess="readOnly"/>
		<field name="packPremia" type="xiDouble" childAccess="readOnly"/>

	
		<!-- ======================================== -->
		<!-- Document tab fields -->
		<!-- ======================================== -->
		<field name="documentsTableModel" type="tableModel" childAccess="full"/>
		<field name="documentTypeModel" type="listModel" childAccess="full"/>
		<field name="docId" type="xiInteger" childAccess="full"/>
		<field name="systemCode" type="xiInteger" childAccess="full"/>
		<field name="system" type="xiString" childAccess="full"/>
		<field name="attachDate" type="xiDate" childAccess="full"/>
		<field name="docDescription" type="xiString" childAccess="full"/>
		<field name="numDocs" type="xiInteger" childAccess="full"/>								

		<!-- ======================================== -->
		<!-- Temporary field until tab model will contain the information -->
		<!-- ======================================== -->
		<field name="lastTabState" type="string" childAccess="full" defaultValue="generalTabsDetailsState"/>


	</context>

</root>
