=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/JavaSource/config/dtd/menu.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by aa (aa) -->
<!--DTD generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->

<!-- Root elements -->

<!ELEMENT root (menuGroup)*>

<!ELEMENT menuGroup (menuItem*)>
<!ATTLIST menuGroup
	name CDATA #REQUIRED
>

<!ELEMENT menuItem EMPTY>
<!ATTLIST menuItem
	id CDATA #REQUIRED
	flowName CDATA #REQUIRED
	openAs (normal | popup | dialog | newWindow) #REQUIRED
	shortDesc CDATA #REQUIRED
	shortCutKey CDATA #IMPLIED
	windowExtraParams CDATA #IMPLIED
>

=== odedns/oldsrc/src/WorkSrc/ness/workspace/FWPilotWeb/WebContent/WEB-INF/classes/config/menu/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "menu.dtd">
<root>

	<menuGroup name="systemMenu">

		<menuItem
			id="batchFlow"
			shortDesc="menuBatch"			
			flowName="batchFlow"
			openAs="normal"/>

		<menuItem
			id="openHeskem"
			shortDesc="menuSearchAgreement"
			shortCutKey="Ctrl+a"
			flowName="serachAgreementFlow"
			openAs="normal"/>

		<menuItem
			id="manageCustomer"
			shortCutKey="Ctrl+m"
			shortDesc="menuManageCustomers"
			flowName="customersFlow"
			openAs="normal"/>			



		<menuItem
			id="searchCustomer"
			shortCutKey="Ctrl+s"
			shortDesc="menuSearchCustomer"
			flowName="searchCustomerFlow"
			openAs="normal"/>			

		<menuItem
			id="checkScreens"
			shortDesc="menuCheckScreens"
			flowName="checkScreensFlow"
			openAs="normal"/>

		<menuItem
			id="checkWindows"
			shortDesc="menuWindows"
			flowName="windowsFlow"
			openAs="normal"/>

	</menuGroup>

	<menuGroup name="agreementMenu">
		<menuItem
			id="openSubflow"
			shortDesc="menuBuildAgreement"
			flowName="buildAgreementFlow"			
			openAs="normal"/>						
	</menuGroup>

	<menuGroup name="searchMenu">
		<menuItem
			id="searchCustomer"
			shortDesc="menuSearchCustomer"
			flowName="searchCustomerFlow"
			openAs="normal"/>
	</menuGroup>

	<menuGroup name="checkScreensMenu">
		<menuItem
			id="checkScreens1"
			shortDesc="checkScreensNormal"
			flowName="serachAgreementFlow"
			openAs="normal"/>

		<menuItem
			id="checkScreens2"
			shortDesc="checkScreensNew"
			flowName="serachAgreementFlow"
			openAs="newWindow"/>

		<menuItem
			id="checkScreens3"
			shortDesc="checkScreensDialog"
			flowName="dialogFlow"
			openAs="dialog"
			windowExtraParams="scroll:no;status:no;dialogHeight:300px;dialogWidth:300px;dialogLeft:200px;dialogTop:200px;"
		/>

		<menuItem
			id="checkScreens4"
			shortDesc="checkScreensPopup"
			flowName="popupFlow"
			openAs="popup"
			windowExtraParams="scroll=no,status=no,height=250,width=350,left=550,top=250"
		/>
	</menuGroup>
</root>
